// Legal pages. Only facts that are known are stated; nothing is invented.
// Business registration data that is not yet verified (address, KvK, BTW) is intentionally not shown —
// see README “Required business data before live deployment”.

import { SITE } from './content.mjs';
const KVK = (l, v) => SITE.kvk ? `<dt>${l}</dt><dd>${SITE.kvk}</dd>` : '';
const ADDR = l => SITE.address && SITE.address.street ? `<dt>${l}</dt><dd>${SITE.address.street}, ${SITE.address.postalCode} ${SITE.address.city}</dd>` : '';
const LEGALNAME = l => SITE.legalName ? `<dt>${l}</dt><dd>${SITE.legalName}</dd>` : '';
const BTW = (l) => SITE.btw ? `<dt>${l}</dt><dd>${SITE.btw}</dd>` : '';
const E = '<a href="mailto:design@gwgraphic.com">design@gwgraphic.com</a>';
const P = '<a href="tel:+31644319415">+31&nbsp;6&nbsp;44&nbsp;31&nbsp;94&nbsp;15</a>';
const AP_NL = '<a href="https://www.autoriteitpersoonsgegevens.nl" rel="noopener" target="_blank">Autoriteit Persoonsgegevens</a>';
const AP_EN = '<a href="https://www.autoriteitpersoonsgegevens.nl/en" rel="noopener" target="_blank">Dutch Data Protection Authority (Autoriteit Persoonsgegevens)</a>';
const AP_PL = '<a href="https://www.autoriteitpersoonsgegevens.nl/en" rel="noopener" target="_blank">holenderski organ ochrony danych (Autoriteit Persoonsgegevens)</a>';

export const LEGAL = {
/* =================================================================== PRIVACY */
privacy: {
nl: { title: 'Privacybeleid', description: 'Hoe GW Graphic Design omgaat met persoonsgegevens van klanten en websitebezoekers.',
  sections: [
  { h: 'Wie is verantwoordelijk?', body: `<p>GW Graphic Design, de studio van Grzegorz Woźniak (Noord-Brabant, Nederland), is verantwoordelijk voor de verwerking van persoonsgegevens zoals beschreven in dit privacybeleid.</p><p>Vragen over privacy of een verzoek over je gegevens? Mail naar ${E} of bel ${P}.</p>` },
  { h: 'Welke gegevens verwerken we?', body: `<ul><li><strong>Contactgegevens</strong> die je zelf aan ons geeft: naam, bedrijfsnaam, e-mailadres en telefoonnummer.</li><li><strong>Projectinformatie</strong> die je ons stuurt: je bericht, gekozen diensten en eventuele bestanden die je per e-mail of WhatsApp meestuurt.</li><li><strong>Klant- en opdrachtgegevens</strong>: offertes, afspraken, facturen en betalingen.</li><li><strong>Technische gegevens</strong>: bij het verzenden van het formulier wordt je IP-adres gehasht (onherkenbaar gemaakt) en maximaal één uur bewaard om misbruik te voorkomen. Onze hostingprovider houdt daarnaast standaard serverlogbestanden bij (zoals IP-adres, tijdstip en opgevraagde pagina) voor beveiliging.</li></ul><p>We vragen niet om bijzondere persoonsgegevens en hebben die ook niet nodig.</p>` },
  { h: 'Waarvoor en op welke grondslag?', body: `<div class="table-wrap"><table><thead><tr><th>Doel</th><th>Grondslag (AVG)</th></tr></thead><tbody>
<tr><td>Je aanvraag beantwoorden en een offerte maken</td><td>Maatregelen op jouw verzoek vóór een overeenkomst (art. 6 lid 1 b)</td></tr>
<tr><td>De opdracht uitvoeren en met je communiceren</td><td>Uitvoering van de overeenkomst (art. 6 lid 1 b)</td></tr>
<tr><td>Facturatie en boekhouding</td><td>Wettelijke verplichting (art. 6 lid 1 c)</td></tr>
<tr><td>Beveiliging van website en formulier, spam- en misbruikpreventie</td><td>Gerechtvaardigd belang (art. 6 lid 1 f)</td></tr>
<tr><td>Afgerond werk tonen in het portfolio</td><td>Gerechtvaardigd belang, of toestemming waar nodig; zie de algemene voorwaarden</td></tr>
</tbody></table></div>` },
  { h: 'Het offerteformulier', body: `<p>Wat je in het formulier invult, wordt via een beveiligde verbinding (HTTPS) naar onze server gestuurd, daar gecontroleerd en als e-mail aan ${E} bezorgd. We gebruiken deze gegevens alleen om je aanvraag te beantwoorden en, als je opdracht geeft, om het project uit te voeren. Het formulier bevat geen trackers en er worden geen bestanden geüpload.</p>` },
  { h: 'Met wie delen we gegevens?', body: `<p>We verkopen geen gegevens en delen ze alleen als dat nodig is voor het doel:</p><ul><li>onze <strong>hosting- en e-mailprovider</strong>, die de website en de mailbox technisch beheert;</li><li>onze <strong>boekhouder of boekhoudsoftware</strong> voor facturen en de administratie;</li><li><strong>productiepartners of vervoerders</strong>, alleen als dat voor jouw opdracht nodig is (bijvoorbeeld een afleveradres).</li></ul><p>Met verwerkers maken we afspraken over beveiliging en vertrouwelijkheid. Neem je contact op via WhatsApp, dan verwerkt WhatsApp (Meta) je gegevens volgens de eigen voorwaarden en het privacybeleid van WhatsApp. Het bekijken van deze website activeert WhatsApp niet.</p>` },
  { h: 'Doorgifte buiten de EER', body: `<p>We kiezen waar mogelijk dienstverleners die gegevens binnen de Europese Economische Ruimte verwerken. Als een dienstverlener gegevens buiten de EER verwerkt, gebeurt dat alleen met een passende waarborg, zoals een adequaatheidsbesluit of de modelcontractbepalingen van de Europese Commissie.</p>` },
  { h: 'Hoe lang bewaren we gegevens?', body: `<ul><li>Aanvragen die niet tot een opdracht leiden: maximaal 12 maanden na het laatste contact.</li><li>Klant- en projectgegevens: zolang de samenwerking loopt en daarna zolang nodig is voor garantie of vragen over het geleverde werk.</li><li>Facturen en de administratie: 7 jaar, zoals de Nederlandse fiscale bewaarplicht voorschrijft.</li><li>Gehashte IP-adressen voor misbruikpreventie: maximaal 1 uur.</li></ul>` },
  { h: 'Beveiliging', body: `<p>We nemen passende technische en organisatorische maatregelen: een versleutelde verbinding (HTTPS), beveiligde serverinstellingen, beperkte toegang tot gegevens, back-ups en regelmatige updates. Het formulier is beschermd tegen spam en misbruik zonder dat daarvoor tracking of CAPTCHA van derden nodig is.</p>` },
  { h: 'Jouw rechten', body: `<p>Je hebt het recht op inzage, rectificatie, verwijdering, beperking van de verwerking, bezwaar en overdraagbaarheid van je gegevens. Heb je toestemming gegeven, dan kun je die altijd intrekken; dat heeft geen gevolgen voor verwerking die al eerder plaatsvond. Stuur je verzoek naar ${E}. We reageren binnen één maand en kunnen vragen je identiteit te bevestigen.</p>` },
  { h: 'Een klacht indienen', body: `<p>Ben je niet tevreden over hoe we met je gegevens omgaan? Laat het ons eerst weten, dan zoeken we samen naar een oplossing. Je hebt ook altijd het recht om een klacht in te dienen bij de ${AP_NL}.</p>` },
  { h: 'Cookies en externe diensten', body: `<p>Deze website gebruikt geen cookies voor statistieken, advertenties of tracking en laadt geen lettertypes, scripts of widgets van derden. Lees meer in het <a href="cookiebeleid.html">cookiebeleid</a>. Links naar Google, WhatsApp, Instagram, Facebook en LinkedIn openen pas een externe dienst als je erop klikt.</p>` },
  { h: 'Wijzigingen', body: `<p>We passen dit privacybeleid aan als onze werkwijze, dienstverleners of de wet veranderen. Bovenaan deze pagina staat de datum van de laatste wijziging.</p>` }
]},
en: { title: 'Privacy policy', description: 'How GW Graphic Design handles the personal data of clients and website visitors.',
  sections: [
  { h: 'Who is responsible?', body: `<p>GW Graphic Design, the studio of Grzegorz Woźniak (North Brabant, the Netherlands), is the controller for the processing of personal data described in this privacy policy.</p><p>Questions about privacy or a request about your data? Email ${E} or call ${P}.</p>` },
  { h: 'What data do we process?', body: `<ul><li><strong>Contact details</strong> you give us: name, company name, email address and phone number.</li><li><strong>Project information</strong> you send us: your message, the services you choose and any files you send by email or WhatsApp.</li><li><strong>Client and order data</strong>: quotes, agreements, invoices and payments.</li><li><strong>Technical data</strong>: when you submit the form, your IP address is hashed (made unrecognisable) and kept for no more than one hour to prevent abuse. Our hosting provider also keeps standard server log files (such as IP address, time and requested page) for security.</li></ul><p>We do not ask for special categories of personal data and do not need them.</p>` },
  { h: 'Purposes and legal bases', body: `<div class="table-wrap"><table><thead><tr><th>Purpose</th><th>Legal basis (GDPR)</th></tr></thead><tbody>
<tr><td>Answering your request and preparing a quote</td><td>Steps taken at your request before entering into a contract (Art. 6(1)(b))</td></tr>
<tr><td>Carrying out the order and communicating with you</td><td>Performance of a contract (Art. 6(1)(b))</td></tr>
<tr><td>Invoicing and accounting</td><td>Legal obligation (Art. 6(1)(c))</td></tr>
<tr><td>Security of the website and form, spam and abuse prevention</td><td>Legitimate interest (Art. 6(1)(f))</td></tr>
<tr><td>Showing completed work in the portfolio</td><td>Legitimate interest, or consent where required; see the terms and conditions</td></tr>
</tbody></table></div>` },
  { h: 'The quote form', body: `<p>What you enter in the form is sent over a secure connection (HTTPS) to our server, checked there and delivered as an email to ${E}. We only use this data to answer your request and, if you place an order, to carry out the project. The form contains no trackers and no files are uploaded.</p>` },
  { h: 'Who do we share data with?', body: `<p>We never sell data and only share it when needed for the purpose:</p><ul><li>our <strong>hosting and email provider</strong>, which runs the website and mailbox;</li><li>our <strong>accountant or accounting software</strong> for invoices and bookkeeping;</li><li><strong>production partners or carriers</strong>, only when your order requires it (for example a delivery address).</li></ul><p>We make agreements on security and confidentiality with processors. If you contact us via WhatsApp, WhatsApp (Meta) processes your data under its own terms and privacy policy. Viewing this website does not activate WhatsApp.</p>` },
  { h: 'Transfers outside the EEA', body: `<p>Where possible we choose service providers that process data within the European Economic Area. If a provider processes data outside the EEA, this only happens with an appropriate safeguard, such as an adequacy decision or the European Commission’s standard contractual clauses.</p>` },
  { h: 'How long do we keep data?', body: `<ul><li>Requests that do not lead to an order: no more than 12 months after the last contact.</li><li>Client and project data: for as long as we work together and afterwards for as long as needed for warranty or questions about the delivered work.</li><li>Invoices and accounting records: 7 years, as required by Dutch tax law.</li><li>Hashed IP addresses for abuse prevention: no more than 1 hour.</li></ul>` },
  { h: 'Security', body: `<p>We take appropriate technical and organisational measures: an encrypted connection (HTTPS), secure server settings, limited access to data, backups and regular updates. The form is protected against spam and abuse without third-party tracking or CAPTCHA.</p>` },
  { h: 'Your rights', body: `<p>You have the right of access, rectification, erasure, restriction of processing, objection and data portability. If you have given consent, you can withdraw it at any time; this does not affect processing that took place before. Send your request to ${E}. We respond within one month and may ask you to confirm your identity.</p>` },
  { h: 'Making a complaint', body: `<p>Not happy with how we handle your data? Please tell us first so we can find a solution together. You always have the right to lodge a complaint with the ${AP_EN}.</p>` },
  { h: 'Cookies and external services', body: `<p>This website does not use cookies for statistics, advertising or tracking and does not load third-party fonts, scripts or widgets. Read more in the <a href="cookies.html">cookie policy</a>. Links to Google, WhatsApp, Instagram, Facebook and LinkedIn only open an external service when you click them.</p>` },
  { h: 'Changes', body: `<p>We update this privacy policy when our way of working, service providers or the law change. The date of the latest change is shown at the top of this page.</p>` }
]},
pl: { title: 'Polityka prywatności', description: 'Jak GW Graphic Design przetwarza dane osobowe klientów i osób odwiedzających stronę.',
  sections: [
  { h: 'Kto jest administratorem danych?', body: `<p>Administratorem danych osobowych opisanych w tej polityce jest GW Graphic Design, studio Grzegorza Woźniaka (Brabancja Północna, Holandia).</p><p>Pytania o prywatność lub wniosek dotyczący Twoich danych? Napisz na ${E} albo zadzwoń: ${P}.</p>` },
  { h: 'Jakie dane przetwarzamy?', body: `<ul><li><strong>Dane kontaktowe</strong>, które sam nam podajesz: imię i nazwisko, nazwa firmy, adres e-mail i numer telefonu.</li><li><strong>Informacje o projekcie</strong>, które nam przesyłasz: wiadomość, wybrane usługi i pliki wysłane e-mailem lub przez WhatsApp.</li><li><strong>Dane klientów i zleceń</strong>: wyceny, ustalenia, faktury i płatności.</li><li><strong>Dane techniczne</strong>: przy wysyłce formularza Twój adres IP jest haszowany (przekształcany w nierozpoznawalną postać) i przechowywany najwyżej godzinę, aby zapobiegać nadużyciom. Nasz dostawca hostingu prowadzi też standardowe logi serwera (np. adres IP, czas, otwierana strona) ze względów bezpieczeństwa.</li></ul><p>Nie prosimy o szczególne kategorie danych osobowych i ich nie potrzebujemy.</p>` },
  { h: 'Cele i podstawy prawne', body: `<div class="table-wrap"><table><thead><tr><th>Cel</th><th>Podstawa prawna (RODO)</th></tr></thead><tbody>
<tr><td>Odpowiedź na zapytanie i przygotowanie wyceny</td><td>Działania na Twoje żądanie przed zawarciem umowy (art. 6 ust. 1 lit. b)</td></tr>
<tr><td>Realizacja zlecenia i kontakt z Tobą</td><td>Wykonanie umowy (art. 6 ust. 1 lit. b)</td></tr>
<tr><td>Fakturowanie i księgowość</td><td>Obowiązek prawny (art. 6 ust. 1 lit. c)</td></tr>
<tr><td>Bezpieczeństwo strony i formularza, ochrona przed spamem i nadużyciami</td><td>Prawnie uzasadniony interes (art. 6 ust. 1 lit. f)</td></tr>
<tr><td>Pokazywanie zrealizowanych prac w portfolio</td><td>Prawnie uzasadniony interes lub zgoda, gdy jest wymagana; zob. regulamin</td></tr>
</tbody></table></div>` },
  { h: 'Formularz zapytania', body: `<p>Dane wpisane w formularzu trafiają bezpiecznym połączeniem (HTTPS) na nasz serwer, są tam sprawdzane i dostarczane jako e-mail na adres ${E}. Wykorzystujemy je wyłącznie do odpowiedzi na zapytanie, a jeśli złożysz zlecenie — do realizacji projektu. Formularz nie zawiera narzędzi śledzących i nie służy do przesyłania plików.</p>` },
  { h: 'Komu przekazujemy dane?', body: `<p>Nie sprzedajemy danych i przekazujemy je tylko wtedy, gdy jest to potrzebne do danego celu:</p><ul><li>naszemu <strong>dostawcy hostingu i poczty e-mail</strong>, który technicznie obsługuje stronę i skrzynkę;</li><li><strong>księgowemu lub programowi księgowemu</strong> — w zakresie faktur i dokumentacji;</li><li><strong>partnerom produkcyjnym lub przewoźnikom</strong> — tylko gdy wymaga tego Twoje zlecenie (np. adres dostawy).</li></ul><p>Z podmiotami przetwarzającymi zawieramy ustalenia dotyczące bezpieczeństwa i poufności. Jeśli kontaktujesz się przez WhatsApp, WhatsApp (Meta) przetwarza Twoje dane na podstawie własnego regulaminu i polityki prywatności. Samo przeglądanie tej strony nie uruchamia WhatsApp.</p>` },
  { h: 'Przekazywanie danych poza EOG', body: `<p>W miarę możliwości wybieramy usługodawców przetwarzających dane w Europejskim Obszarze Gospodarczym. Jeśli usługodawca przetwarza dane poza EOG, odbywa się to wyłącznie z odpowiednim zabezpieczeniem, np. na podstawie decyzji stwierdzającej odpowiedni stopień ochrony lub standardowych klauzul umownych Komisji Europejskiej.</p>` },
  { h: 'Jak długo przechowujemy dane?', body: `<ul><li>Zapytania, które nie prowadzą do zlecenia: najwyżej 12 miesięcy od ostatniego kontaktu.</li><li>Dane klientów i projektów: przez czas współpracy, a następnie tak długo, jak to potrzebne w związku z gwarancją lub pytaniami o wykonaną pracę.</li><li>Faktury i dokumentacja księgowa: 7 lat, zgodnie z holenderskim obowiązkiem podatkowym.</li><li>Haszowane adresy IP (ochrona przed nadużyciami): najwyżej 1 godzinę.</li></ul>` },
  { h: 'Bezpieczeństwo', body: `<p>Stosujemy odpowiednie środki techniczne i organizacyjne: szyfrowane połączenie (HTTPS), bezpieczną konfigurację serwera, ograniczony dostęp do danych, kopie zapasowe i regularne aktualizacje. Formularz jest chroniony przed spamem i nadużyciami bez śledzenia i bez zewnętrznej CAPTCHA.</p>` },
  { h: 'Twoje prawa', body: `<p>Masz prawo dostępu do danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, sprzeciwu oraz przenoszenia danych. Jeśli wyraziłeś zgodę, możesz ją w każdej chwili wycofać; nie wpływa to na zgodność z prawem wcześniejszego przetwarzania. Wniosek wyślij na ${E}. Odpowiadamy w ciągu miesiąca i możemy poprosić o potwierdzenie tożsamości.</p>` },
  { h: 'Skarga', body: `<p>Jeśli nie odpowiada Ci sposób, w jaki przetwarzamy dane, daj nam najpierw znać — poszukamy rozwiązania. Zawsze masz też prawo złożyć skargę do organu nadzorczego: ${AP_PL}.</p>` },
  { h: 'Cookies i usługi zewnętrzne', body: `<p>Ta strona nie używa cookies do statystyk, reklam ani śledzenia i nie wczytuje zewnętrznych czcionek, skryptów ani widżetów. Więcej w <a href="polityka-cookies.html">polityce cookies</a>. Linki do Google, WhatsApp, Instagrama, Facebooka i LinkedIn otwierają usługę zewnętrzną dopiero po kliknięciu.</p>` },
  { h: 'Zmiany', body: `<p>Aktualizujemy tę politykę, gdy zmienia się nasz sposób pracy, usługodawcy lub przepisy. Data ostatniej zmiany znajduje się na górze strony.</p>` }
]}
},

/* =================================================================== COOKIES */
cookies: {
nl: { title: 'Cookiebeleid', description: 'Welke cookies en opslag de website van GW Graphic Design gebruikt: geen tracking, geen advertenties, geen diensten van derden.',
  sections: [
  { h: 'Kort gezegd', body: `<p>Deze website plaatst <strong>geen cookies</strong> en gebruikt geen analytics, advertentienetwerken, social-media-pixels of andere trackers. Lettertypes, afbeeldingen en scripts worden allemaal vanaf onze eigen server geladen. Daarom tonen we ook geen cookiebanner: er is niets om toestemming voor te vragen.</p>` },
  { h: 'Wat wordt er wel opgeslagen?', body: `<div class="table-wrap"><table><thead><tr><th>Naam</th><th>Type</th><th>Doel</th><th>Bewaartermijn</th></tr></thead><tbody>
<tr><td><code>gwIntroVisits</code></td><td>localStorage</td><td>Telt je bezoeken (één per browsersessie), zodat vanaf het vierde bezoek de optie verschijnt om de openingsanimatie uit te zetten.</td><td>Tot je het wist via Cookie-instellingen of je browser</td></tr><tr><td><code>gwIntroDisabled</code></td><td>localStorage</td><td>Alleen als je zelf kiest voor ‘Animatie niet meer tonen’: onthoudt die keuze.</td><td>Tot je het wist of de animatie weer inschakelt</td></tr><tr><td><code>gwIntroSession</code></td><td>sessionStorage</td><td>Voorkomt dat de animatie binnen hetzelfde bezoek opnieuw start.</td><td>Tot je het tabblad sluit</td></tr>
</tbody></table></div><p>Dit zijn functionele voorkeuren: ze blijven op je eigen apparaat, worden niet naar ons verstuurd, worden niet gebruikt voor statistieken of reclame en zijn niet te herleiden tot jou als persoon.</p>` },
  { h: 'Serverlogbestanden', body: `<p>Zoals elke website registreert onze hostingprovider technische gegevens van verzoeken aan de server (zoals IP-adres, tijdstip en opgevraagde pagina) om de website veilig en bereikbaar te houden. Dit gebeurt zonder cookies. Meer hierover lees je in het <a href="privacybeleid.html">privacybeleid</a>.</p>` },
  { h: 'Externe links', body: `<p>Links naar Google Reviews, WhatsApp, Instagram, Facebook en LinkedIn openen de betreffende dienst pas als je erop klikt. Vanaf dat moment gelden de cookie- en privacyregels van die dienst.</p>` },
  { h: 'Je keuze beheren', body: `<p>Via <strong>Cookie-instellingen</strong> onderaan elke pagina zie je dit overzicht en kun je de opgeslagen gegevens direct wissen. Je kunt de opslag ook altijd verwijderen via de instellingen van je browser.</p>` },
  { h: 'Wijzigingen', body: `<p>Gaan we ooit statistieken of andere niet-noodzakelijke technieken gebruiken, dan passen we dit beleid vooraf aan en vragen we waar nodig eerst je toestemming, met een even makkelijke keuze om te weigeren.</p>` }
]},
en: { title: 'Cookie policy', description: 'Which cookies and storage the GW Graphic Design website uses: no tracking, no advertising, no third-party services.',
  sections: [
  { h: 'In short', body: `<p>This website sets <strong>no cookies</strong> and uses no analytics, advertising networks, social media pixels or other trackers. Fonts, images and scripts are all loaded from our own server. That is also why there is no cookie banner: there is nothing to ask consent for.</p>` },
  { h: 'What is stored?', body: `<div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Purpose</th><th>Retention</th></tr></thead><tbody>
<tr><td><code>gwIntroVisits</code></td><td>localStorage</td><td>Counts your visits (one per browser session), so that from the fourth visit you get the option to switch the opening animation off.</td><td>Until you clear it via Cookie settings or your browser</td></tr><tr><td><code>gwIntroDisabled</code></td><td>localStorage</td><td>Only if you choose ‘Don’t show again’ yourself: remembers that choice.</td><td>Until you clear it or switch the animation back on</td></tr><tr><td><code>gwIntroSession</code></td><td>sessionStorage</td><td>Prevents the animation from starting again during the same visit.</td><td>Until you close the tab</td></tr>
</tbody></table></div><p>These are functional preferences: they stay on your own device, are never sent to us, are not used for statistics or advertising and cannot identify you.</p>` },
  { h: 'Server log files', body: `<p>Like every website, our hosting provider records technical data about requests to the server (such as IP address, time and requested page) to keep the website secure and available. This happens without cookies. Read more in the <a href="privacy.html">privacy policy</a>.</p>` },
  { h: 'External links', body: `<p>Links to Google Reviews, WhatsApp, Instagram, Facebook and LinkedIn only open that service when you click them. From then on, that service’s cookie and privacy rules apply.</p>` },
  { h: 'Managing your choice', body: `<p>Use <strong>Cookie settings</strong> at the bottom of every page to see this overview and clear stored data straight away. You can also delete storage at any time in your browser settings.</p>` },
  { h: 'Changes', body: `<p>If we ever start using statistics or other non-essential technologies, we will update this policy first and, where required, ask for your consent beforehand, with an equally easy option to refuse.</p>` }
]},
pl: { title: 'Polityka cookies', description: 'Jakich plików cookies i pamięci używa strona GW Graphic Design: bez śledzenia, bez reklam, bez usług zewnętrznych.',
  sections: [
  { h: 'W skrócie', body: `<p>Ta strona <strong>nie zapisuje plików cookies</strong> i nie używa narzędzi analitycznych, sieci reklamowych, pikseli mediów społecznościowych ani innych narzędzi śledzących. Czcionki, zdjęcia i skrypty ładowane są z naszego serwera. Dlatego nie wyświetlamy banera cookies — nie ma na co wyrażać zgody.</p>` },
  { h: 'Co jest zapisywane?', body: `<div class="table-wrap"><table><thead><tr><th>Nazwa</th><th>Rodzaj</th><th>Cel</th><th>Okres przechowywania</th></tr></thead><tbody>
<tr><td><code>gwIntroVisits</code></td><td>localStorage</td><td>Liczy wizyty (jedna na sesję przeglądarki), żeby od czwartej wizyty pokazać opcję wyłączenia animacji otwarcia.</td><td>Do usunięcia w Ustawieniach cookies lub w przeglądarce</td></tr><tr><td><code>gwIntroDisabled</code></td><td>localStorage</td><td>Tylko jeśli sam wybierzesz „Nie pokazuj ponownie”: zapamiętuje ten wybór.</td><td>Do usunięcia lub ponownego włączenia animacji</td></tr><tr><td><code>gwIntroSession</code></td><td>sessionStorage</td><td>Zapobiega ponownemu uruchomieniu animacji w trakcie tej samej wizyty.</td><td>Do zamknięcia karty</td></tr>
</tbody></table></div><p>To funkcjonalne preferencje: zostają na Twoim urządzeniu, nie są do nas wysyłane, nie służą do statystyk ani reklam i nie pozwalają Cię zidentyfikować.</p>` },
  { h: 'Logi serwera', body: `<p>Jak każda strona, nasz dostawca hostingu rejestruje dane techniczne zapytań do serwera (np. adres IP, czas i otwieraną stronę), aby zapewnić bezpieczeństwo i dostępność. Odbywa się to bez cookies. Więcej w <a href="polityka-prywatnosci.html">polityce prywatności</a>.</p>` },
  { h: 'Linki zewnętrzne', body: `<p>Linki do opinii Google, WhatsApp, Instagrama, Facebooka i LinkedIn otwierają daną usługę dopiero po kliknięciu. Od tej chwili obowiązują zasady cookies i prywatności tej usługi.</p>` },
  { h: 'Zarządzanie wyborem', body: `<p>W <strong>Ustawieniach cookies</strong> na dole każdej strony zobaczysz to zestawienie i od razu wyczyścisz zapisane dane. Możesz je też w każdej chwili usunąć w ustawieniach przeglądarki.</p>` },
  { h: 'Zmiany', body: `<p>Jeśli kiedykolwiek zaczniemy używać statystyk lub innych nieniezbędnych technologii, najpierw zaktualizujemy tę politykę i — tam, gdzie to wymagane — poprosimy o zgodę, z równie łatwą możliwością odmowy.</p>` }
]}
},

/* =================================================================== TERMS */
terms: {
nl: { title: 'Algemene voorwaarden', description: 'De algemene voorwaarden van GW Graphic Design voor grafisch ontwerp, drukwerk, kleding, belettering, websites en montage.',
  sections: [
  { h: 'Toepassing', body: `<p>Deze voorwaarden gelden voor alle offertes, opdrachten en leveringen van GW Graphic Design (Grzegorz Woźniak), tenzij in de offerte of een schriftelijke overeenkomst iets anders is afgesproken. Ze gelden voor onder meer grafisch ontwerp, logo en huisstijl, drukwerk, bedrukte kleding, borden en signing, autobelettering en voertuiggraphics, raambelettering, websites, relatiegeschenken en montage.</p>` },
  { h: 'Offertes en opdracht', body: `<p>Een offerte is gebaseerd op de informatie die op dat moment bekend is en is 30 dagen geldig, tenzij anders vermeld. Een opdracht komt tot stand zodra je de offerte schriftelijk (ook per e-mail of WhatsApp) accepteert. Wijzigingen of extra werk buiten de afgesproken omvang bespreken we vooraf en kunnen apart worden geoffreerd.</p>` },
  { h: 'Aanbetaling en betaling', body: `<p>Voor de start van een project kan een aanbetaling worden gevraagd, meestal 50%. Het restant en eventuele termijnen staan in de offerte of op de factuur. Facturen worden betaald binnen de termijn op de factuur. Zolang een opeisbare betaling openstaat, kunnen productie, levering van definitieve bestanden of montage worden uitgesteld.</p>` },
  { h: 'Aangeleverd materiaal', body: `<p>Je bent verantwoordelijk voor de juistheid van teksten, namen, contactgegevens, afmetingen en ander materiaal dat je aanlevert, en je verklaart dat je het recht hebt dit materiaal te laten gebruiken. We voeren geen opdrachten uit met onrechtmatige of inbreukmakende inhoud.</p>` },
  { h: 'Proef en akkoord', body: `<p>Voordat iets in productie gaat, ontvang je een ontwerp of proef ter controle. Controleer spelling, cijfers, kleuren, maten en plaatsing zorgvuldig. Na jouw akkoord gaat het werk in productie. Fouten die na akkoord in de goedgekeurde proef blijken te staan, komen voor jouw rekening; fouten in onze eigen uitvoering herstellen wij.</p>` },
  { h: 'Correctierondes', body: `<p>Het aantal inbegrepen ontwerpvoorstellen en correctierondes staat in de offerte. Extra rondes, een nieuwe richting of extra onderdelen bespreken we vooraf.</p>` },
  { h: 'Kleur, materiaal en toleranties', body: `<p>Kleuren op een scherm kunnen afwijken van kleuren op papier, textiel of folie. Kleine afwijkingen in kleur, snijden, plaatsing, bedrukking, materiaalpartijen of maatvoering binnen gangbare vaknormen zijn geen gebrek. Beperkingen van een specifiek materiaal bespreken we vooraf.</p>` },
  { h: 'Belettering en montage', body: `<p>Meld vóór de montage schade, overgespoten delen, coatings, reparaties of andere bijzonderheden aan de ondergrond. Hechting en latere verwijdering hangen af van de staat en leeftijd van de lak of het glas, eerdere reparaties, temperatuur en de ondergrond. Het voertuig of de ruit moet op de afgesproken tijd schoon en bereikbaar zijn. Specifieke risico’s leggen we vóór de montage met je vast.</p>` },
  { h: 'Websites', body: `<p>Een website omvat de functies en inhoud die in de offerte staan. Hosting, domeinnaam, betaalde plug-ins, licenties van derden, onderhoud, teksten en updates zijn alleen inbegrepen als dat uitdrukkelijk is afgesproken. Na oplevering ben je zelf verantwoordelijk voor updates, back-ups en beveiliging, tenzij een onderhoudsafspraak iets anders bepaalt.</p>` },
  { h: 'Intellectueel eigendom', body: `<p>Schetsen, niet gekozen voorstellen en werkbestanden blijven eigendom van GW Graphic Design, tenzij anders afgesproken. Na volledige betaling krijg je de gebruiksrechten op het definitieve ontwerp zoals omschreven in de offerte. Lettertypes, beeldmateriaal, plug-ins en software van derden vallen onder hun eigen licenties.</p>` },
  { h: 'Portfolio', body: `<p>Tenzij vooraf vertrouwelijkheid is afgesproken, mag GW Graphic Design opgeleverd werk dat publiek zichtbaar is tonen in het portfolio en op sociale media. Wil je dat niet, laat het ons dan schriftelijk weten vóór publicatie.</p>` },
  { h: 'Levering en planning', body: `<p>Opgegeven termijnen zijn een inschatting en hangen af van tijdige feedback, betaling, beschikbaarheid van materiaal en productie door derden. Bij vertraging buiten onze invloed informeren we je zo snel mogelijk over een nieuwe planning.</p>` },
  { h: 'Annulering', body: `<p>Annuleer je een opdracht nadat het werk is gestart, dan betaal je het werk dat al is uitgevoerd en de kosten die al onherroepelijk bij derden zijn gemaakt. Voor consumenten gelden de wettelijke rechten; op maat gemaakte en gepersonaliseerde producten zijn wettelijk uitgezonderd van het herroepingsrecht.</p>` },
  { h: 'Klachten', body: `<p>Meld zichtbare gebreken of ontbrekende onderdelen zo snel mogelijk na levering, bij voorkeur met foto’s. We zoeken samen naar een passende oplossing. Dit laat je wettelijke rechten onverlet.</p>` },
  { h: 'Aansprakelijkheid', body: `<p>Voor zover de wet dat toestaat, is GW Graphic Design niet aansprakelijk voor indirecte schade of gevolgschade en is de aansprakelijkheid beperkt tot het factuurbedrag van de betreffende opdracht. Deze beperking geldt niet bij opzet of bewuste roekeloosheid, of waar de wet een beperking niet toestaat.</p>` },
  { h: 'Consumenten', body: `<p>Ben je consument, dan gaan dwingende regels van consumentenrecht voor op bepalingen in deze voorwaarden die daarmee in strijd zijn.</p>` },
  { h: 'Toepasselijk recht', body: `<p>Op alle opdrachten is Nederlands recht van toepassing. We proberen geschillen eerst samen op te lossen voordat een van beide partijen naar de bevoegde rechter stapt.</p>` }
]},
en: { title: 'Terms and conditions', description: 'The terms and conditions of GW Graphic Design for graphic design, print, apparel, vehicle graphics, websites and installation.',
  sections: [
  { h: 'Scope', body: `<p>These terms apply to all quotes, orders and deliveries by GW Graphic Design (Grzegorz Woźniak) unless the quote or a written agreement states otherwise. They cover, among other things, graphic design, logo and visual identity, print, printed apparel, signs and signage, vehicle lettering and graphics, window graphics, websites, promotional products and installation.</p>` },
  { h: 'Quotes and orders', body: `<p>A quote is based on the information known at the time and is valid for 30 days unless stated otherwise. An order is placed as soon as you accept the quote in writing (including by email or WhatsApp). Changes or extra work outside the agreed scope are discussed in advance and may be quoted separately.</p>` },
  { h: 'Deposit and payment', body: `<p>A deposit, usually 50%, may be requested before a project starts. The balance and any instalments are stated in the quote or on the invoice. Invoices are paid within the term stated on the invoice. While a due payment is outstanding, production, delivery of final files or installation may be postponed.</p>` },
  { h: 'Materials you supply', body: `<p>You are responsible for the accuracy of text, names, contact details, dimensions and other material you supply, and you confirm that you have the right to have this material used. We do not carry out orders with unlawful or infringing content.</p>` },
  { h: 'Proof and approval', body: `<p>Before anything goes into production, you receive a design or proof to check. Please check spelling, numbers, colours, dimensions and placement carefully. After your approval the work goes into production. Errors found after approval that were in the approved proof are at your expense; errors in our own execution we put right.</p>` },
  { h: 'Revisions', body: `<p>The number of included design proposals and revision rounds is stated in the quote. Extra rounds, a new direction or additional items are discussed in advance.</p>` },
  { h: 'Colour, materials and tolerances', body: `<p>Colours on a screen may differ from colours on paper, textiles or vinyl. Small deviations in colour, cutting, placement, printing, material batches or dimensions within normal industry standards are not a defect. Limitations of a specific material are discussed in advance.</p>` },
  { h: 'Lettering and installation', body: `<p>Before installation, tell us about damage, resprayed parts, coatings, repairs or other particularities of the surface. Adhesion and later removal depend on the condition and age of the paint or glass, previous repairs, temperature and the surface. The vehicle or window must be clean and accessible at the agreed time. Specific risks are recorded with you before installation.</p>` },
  { h: 'Websites', body: `<p>A website includes the features and content stated in the quote. Hosting, domain name, paid plugins, third-party licences, maintenance, copywriting and updates are only included when explicitly agreed. After delivery you are responsible for updates, backups and security unless a maintenance agreement says otherwise.</p>` },
  { h: 'Intellectual property', body: `<p>Sketches, unchosen proposals and working files remain the property of GW Graphic Design unless agreed otherwise. After full payment you receive the usage rights to the final design as described in the quote. Third-party fonts, images, plugins and software are subject to their own licences.</p>` },
  { h: 'Portfolio', body: `<p>Unless confidentiality was agreed in advance, GW Graphic Design may show delivered work that is publicly visible in its portfolio and on social media. If you do not want this, please tell us in writing before publication.</p>` },
  { h: 'Delivery and planning', body: `<p>Stated lead times are estimates and depend on timely feedback, payment, material availability and production by third parties. If a delay beyond our control occurs, we will inform you of a new schedule as soon as possible.</p>` },
  { h: 'Cancellation', body: `<p>If you cancel an order after work has started, you pay for the work already done and the costs already irrevocably incurred with third parties. Consumers keep their statutory rights; custom-made and personalised products are legally exempt from the right of withdrawal.</p>` },
  { h: 'Complaints', body: `<p>Report visible defects or missing items as soon as possible after delivery, preferably with photos. We will work with you to find a suitable solution. This does not affect your statutory rights.</p>` },
  { h: 'Liability', body: `<p>To the extent permitted by law, GW Graphic Design is not liable for indirect or consequential damage, and liability is limited to the invoice amount of the order concerned. This limitation does not apply in case of intent or deliberate recklessness, or where the law does not allow a limitation.</p>` },
  { h: 'Consumers', body: `<p>If you are a consumer, mandatory consumer law takes precedence over any conflicting provision in these terms.</p>` },
  { h: 'Governing law', body: `<p>Dutch law applies to all orders. We first try to resolve disputes together before either party goes to the competent court.</p>` }
]},
pl: { title: 'Regulamin', description: 'Ogólne warunki współpracy z GW Graphic Design: projektowanie, druk, odzież, oklejanie aut, strony www i montaż.',
  sections: [
  { h: 'Zakres', body: `<p>Niniejsze warunki dotyczą wszystkich wycen, zleceń i dostaw realizowanych przez GW Graphic Design (Grzegorz Woźniak), chyba że wycena lub pisemna umowa stanowi inaczej. Obejmują m.in. projektowanie graficzne, logo i identyfikację wizualną, druk, nadruki na odzieży, tablice i oznakowanie, oklejanie i grafikę na pojazdach, oklejanie szyb i witryn, strony www, gadżety reklamowe oraz montaż.</p>` },
  { h: 'Wyceny i zlecenia', body: `<p>Wycena opiera się na informacjach znanych w chwili jej przygotowania i jest ważna 30 dni, chyba że wskazano inaczej. Zlecenie zostaje przyjęte z chwilą pisemnej akceptacji wyceny (także e-mailem lub przez WhatsApp). Zmiany i prace wykraczające poza ustalony zakres omawiamy wcześniej i mogą być wycenione osobno.</p>` },
  { h: 'Zaliczka i płatność', body: `<p>Przed rozpoczęciem projektu możemy poprosić o zaliczkę, zwykle 50%. Pozostała kwota i ewentualne raty są określone w wycenie lub na fakturze. Faktury opłaca się w terminie wskazanym na fakturze. Dopóki wymagalna płatność pozostaje nieuregulowana, produkcja, przekazanie plików końcowych lub montaż mogą zostać wstrzymane.</p>` },
  { h: 'Materiały od klienta', body: `<p>Odpowiadasz za poprawność tekstów, nazw, danych kontaktowych, wymiarów i innych przekazanych materiałów oraz potwierdzasz, że masz prawo do ich wykorzystania. Nie realizujemy zleceń z treściami niezgodnymi z prawem lub naruszającymi prawa innych osób.</p>` },
  { h: 'Projekt do akceptacji', body: `<p>Zanim cokolwiek trafi do produkcji, otrzymasz projekt lub próbę do sprawdzenia. Dokładnie sprawdź pisownię, liczby, kolory, wymiary i rozmieszczenie. Po Twojej akceptacji praca trafia do produkcji. Błędy zawarte w zaakceptowanym projekcie obciążają Ciebie; błędy w naszym wykonaniu naprawiamy.</p>` },
  { h: 'Poprawki', body: `<p>Liczba propozycji projektowych i rund poprawek wliczonych w cenę jest podana w wycenie. Dodatkowe rundy, nowy kierunek lub dodatkowe elementy omawiamy wcześniej.</p>` },
  { h: 'Kolory, materiały i tolerancje', body: `<p>Kolory na ekranie mogą różnić się od kolorów na papierze, tkaninie czy folii. Niewielkie odchylenia koloru, cięcia, rozmieszczenia, nadruku, partii materiału lub wymiarów w granicach przyjętych w branży nie są wadą. Ograniczenia konkretnego materiału omawiamy wcześniej.</p>` },
  { h: 'Oklejanie i montaż', body: `<p>Przed montażem poinformuj nas o uszkodzeniach, lakierowanych elementach, powłokach, naprawach lub innych szczególnych cechach podłoża. Przyczepność i późniejsze usunięcie folii zależą od stanu i wieku lakieru lub szkła, wcześniejszych napraw, temperatury i podłoża. Pojazd lub szyba muszą być czyste i dostępne w umówionym terminie. Szczególne ryzyka ustalamy z Tobą przed montażem.</p>` },
  { h: 'Strony www', body: `<p>Strona obejmuje funkcje i treści wskazane w wycenie. Hosting, domena, płatne wtyczki, licencje zewnętrzne, utrzymanie, teksty i aktualizacje są wliczone tylko wtedy, gdy wyraźnie to uzgodniono. Po przekazaniu strony odpowiadasz za aktualizacje, kopie zapasowe i bezpieczeństwo, chyba że umowa serwisowa stanowi inaczej.</p>` },
  { h: 'Prawa autorskie', body: `<p>Szkice, niewybrane propozycje i pliki robocze pozostają własnością GW Graphic Design, chyba że ustalono inaczej. Po pełnej zapłacie otrzymujesz prawa do korzystania z ostatecznego projektu w zakresie opisanym w wycenie. Czcionki, zdjęcia, wtyczki i oprogramowanie podmiotów trzecich podlegają ich własnym licencjom.</p>` },
  { h: 'Portfolio', body: `<p>Jeśli wcześniej nie uzgodniono poufności, GW Graphic Design może pokazywać publicznie widoczne, zrealizowane prace w portfolio i mediach społecznościowych. Jeśli sobie tego nie życzysz, poinformuj nas o tym na piśmie przed publikacją.</p>` },
  { h: 'Terminy realizacji', body: `<p>Podane terminy są szacunkowe i zależą od terminowej informacji zwrotnej, płatności, dostępności materiałów i produkcji u podwykonawców. W razie opóźnienia niezależnego od nas jak najszybciej przekażemy nowy harmonogram.</p>` },
  { h: 'Rezygnacja', body: `<p>Jeśli zrezygnujesz ze zlecenia po rozpoczęciu prac, płacisz za wykonaną już pracę i koszty nieodwołalnie poniesione u podmiotów trzecich. Konsumentom przysługują prawa ustawowe; produkty wykonane na zamówienie i personalizowane są z mocy prawa wyłączone z prawa odstąpienia od umowy.</p>` },
  { h: 'Reklamacje', body: `<p>Widoczne wady lub braki zgłoś jak najszybciej po dostawie, najlepiej ze zdjęciami. Wspólnie znajdziemy odpowiednie rozwiązanie. Nie ogranicza to Twoich praw ustawowych.</p>` },
  { h: 'Odpowiedzialność', body: `<p>W zakresie dozwolonym przez prawo GW Graphic Design nie odpowiada za szkody pośrednie ani utracone korzyści, a odpowiedzialność jest ograniczona do kwoty faktury za dane zlecenie. Ograniczenie nie dotyczy winy umyślnej lub rażącego niedbalstwa ani sytuacji, w których prawo nie dopuszcza ograniczenia.</p>` },
  { h: 'Konsumenci', body: `<p>Jeśli jesteś konsumentem, bezwzględnie obowiązujące przepisy prawa konsumenckiego mają pierwszeństwo przed sprzecznymi z nimi postanowieniami tych warunków.</p>` },
  { h: 'Prawo właściwe', body: `<p>Do wszystkich zleceń stosuje się prawo holenderskie. Spory staramy się najpierw rozwiązać wspólnie, zanim którakolwiek ze stron zwróci się do właściwego sądu.</p>` }
]}
},

/* =================================================================== LEGAL NOTICE */
notice: {
nl: { title: 'Colofon', description: 'Bedrijfsgegevens en colofon van GW Graphic Design, studio voor grafisch ontwerp, reclame en belettering.',
  sections: [
  { h: 'Bedrijfsgegevens', body: `<dl><dt>Handelsnaam</dt><dd>GW Graphic Design</dd>${LEGALNAME('Statutaire naam')}<dt>Eigenaar</dt><dd>Grzegorz Woźniak</dd>${ADDR('Adres')}${KVK('KvK-nummer')}${BTW('Btw-id')}<dt>Regio</dt><dd>Noord-Brabant, Nederland</dd><dt>E-mail</dt><dd>${E}</dd><dt>Telefoon</dt><dd>${P}</dd><dt>Website</dt><dd><a href="https://www.gwgraphic.com/">www.gwgraphic.com</a></dd></dl>` },
  { h: 'Werkgebied', body: `<p>Ontwerp en productie voor opdrachtgevers in heel Nederland, België en Duitsland. Montage van belettering op locatie.</p>` },
  { h: 'Ontwerp en realisatie', body: `<p>Ontwerp en inhoud van deze website: GW Graphic Design. Lettertype: Archivo (SIL Open Font License), zelf gehost.</p>` },
  { h: 'Auteursrecht', body: `<p>Het ontwerp van deze website, het GW Graphic Design-logo en de presentatie van het portfolio zijn auteursrechtelijk beschermd. Logo’s en merken van klanten blijven eigendom van de betreffende klant en worden getoond als voorbeeld van uitgevoerd werk.</p>` },
  { h: 'Externe links', body: `<p>Links naar externe websites zijn bedoeld als service. Voor de inhoud, voorwaarden en privacypraktijken van die websites zijn wij niet verantwoordelijk.</p>` }
]},
en: { title: 'Legal notice', description: 'Business details and legal notice of GW Graphic Design, graphic design, advertising and vehicle graphics studio.',
  sections: [
  { h: 'Business details', body: `<dl><dt>Trading name</dt><dd>GW Graphic Design</dd>${LEGALNAME('Registered name')}<dt>Owner</dt><dd>Grzegorz Woźniak</dd>${ADDR('Address')}${KVK('Chamber of Commerce (KvK)')}${BTW('VAT ID')}<dt>Region</dt><dd>North Brabant, the Netherlands</dd><dt>Email</dt><dd>${E}</dd><dt>Phone</dt><dd>${P}</dd><dt>Website</dt><dd><a href="https://www.gwgraphic.com/">www.gwgraphic.com</a></dd></dl>` },
  { h: 'Service area', body: `<p>Design and production for clients across the Netherlands, Belgium and Germany. Installation of lettering on location.</p>` },
  { h: 'Design and development', body: `<p>Design and content of this website: GW Graphic Design. Typeface: Archivo (SIL Open Font License), self-hosted.</p>` },
  { h: 'Copyright', body: `<p>The design of this website, the GW Graphic Design logo and the portfolio presentation are protected by copyright. Client logos and trademarks remain the property of the client concerned and are shown as examples of completed work.</p>` },
  { h: 'External links', body: `<p>Links to external websites are provided as a service. We are not responsible for the content, terms or privacy practices of those websites.</p>` }
]},
pl: { title: 'Nota prawna', description: 'Dane firmy i nota prawna GW Graphic Design, studia projektowania graficznego, reklamy i oklejania.',
  sections: [
  { h: 'Dane firmy', body: `<dl><dt>Nazwa handlowa</dt><dd>GW Graphic Design</dd>${LEGALNAME('Pełna nazwa firmy')}<dt>Właściciel</dt><dd>Grzegorz Woźniak</dd>${ADDR('Adres')}${KVK('Numer KvK')}${BTW('Numer VAT (BTW)')}<dt>Region</dt><dd>Brabancja Północna, Holandia</dd><dt>E-mail</dt><dd>${E}</dd><dt>Telefon</dt><dd>${P}</dd><dt>Strona</dt><dd><a href="https://www.gwgraphic.com/">www.gwgraphic.com</a></dd></dl>` },
  { h: 'Obszar działania', body: `<p>Projekt i produkcja dla klientów z całej Holandii, Belgii i Niemiec. Montaż oklejenia na miejscu.</p>` },
  { h: 'Projekt i wykonanie', body: `<p>Projekt i treści tej strony: GW Graphic Design. Krój pisma: Archivo (SIL Open Font License), hostowany lokalnie.</p>` },
  { h: 'Prawa autorskie', body: `<p>Projekt tej strony, logo GW Graphic Design i prezentacja portfolio są chronione prawem autorskim. Logo i znaki towarowe klientów pozostają własnością tych klientów i są pokazane jako przykłady zrealizowanych prac.</p>` },
  { h: 'Linki zewnętrzne', body: `<p>Linki do stron zewnętrznych podajemy dla wygody. Nie odpowiadamy za treści, regulaminy ani praktyki prywatności tych stron.</p>` }
]}
},

/* =================================================================== ACCESSIBILITY */
a11y: {
nl: { title: 'Toegankelijkheid', description: 'Hoe de website van GW Graphic Design toegankelijk is gemaakt en hoe je een probleem kunt melden.',
  sections: [
  { h: 'Ons uitgangspunt', body: `<p>We willen dat iedereen deze website kan gebruiken, ook met een toetsenbord, een schermlezer, vergroting of een trage verbinding. We streven naar de richtlijnen van WCAG 2.2 op niveau AA.</p>` },
  { h: 'Wat we hebben gedaan', body: `<ul><li>Alle functies werken met het toetsenbord, met een duidelijk zichtbare focus.</li><li>Een logische kopstructuur, herkenbare oriëntatiepunten en een link om direct naar de inhoud te gaan.</li><li>Beschrijvende alternatieve teksten bij alle portfoliofoto’s.</li><li>Voldoende kleurcontrast en tekst die meeschaalt met je browserinstellingen.</li><li>Formuliervelden met labels en foutmeldingen die door hulpsoftware worden voorgelezen.</li><li>Als je besturingssysteem vraagt om minder beweging, worden animaties uitgeschakeld en zie je direct de rustige eindstand.</li><li>Lichte pagina’s zonder trackers, zodat de site ook op een trage verbinding snel laadt.</li></ul>` },
  { h: 'Bekende beperkingen', body: `<p>De Google-reviews zijn in het Engels gepubliceerd. Op deze pagina staat een Nederlandse vertaling, duidelijk gemarkeerd, met het origineel eronder. Beide teksten hebben de juiste taalcode, zodat schermlezers de juiste uitspraak gebruiken.</p>` },
  { h: 'Probleem gevonden?', body: `<p>Loop je ergens tegenaan? Laat het ons weten via ${E} of ${P}. We reageren zo snel mogelijk en helpen je in de tussentijd graag op een andere manier.</p>` }
]},
en: { title: 'Accessibility', description: 'How the GW Graphic Design website has been made accessible and how to report a problem.',
  sections: [
  { h: 'Our starting point', body: `<p>We want everyone to be able to use this website, including with a keyboard, a screen reader, magnification or a slow connection. We aim to meet the WCAG 2.2 guidelines at level AA.</p>` },
  { h: 'What we have done', body: `<ul><li>All features work with the keyboard, with a clearly visible focus.</li><li>A logical heading structure, recognisable landmarks and a link to skip straight to the content.</li><li>Descriptive alternative text for every portfolio photo.</li><li>Sufficient colour contrast and text that scales with your browser settings.</li><li>Form fields with labels and error messages that are announced by assistive technology.</li><li>If your operating system asks for reduced motion, animations are switched off and you see the calm final state straight away.</li><li>Lightweight pages without trackers, so the site loads quickly even on a slow connection.</li></ul>` },
  { h: 'Known limitations', body: `<p>The Google reviews are shown in the original language (English) in which clients wrote them. They are marked as such so that screen readers use the right pronunciation.</p>` },
  { h: 'Found a problem?', body: `<p>Running into something? Let us know via ${E} or ${P}. We will respond as soon as possible and are happy to help you another way in the meantime.</p>` }
]},
pl: { title: 'Dostępność', description: 'Jak zadbaliśmy o dostępność strony GW Graphic Design i jak zgłosić problem.',
  sections: [
  { h: 'Nasze założenia', body: `<p>Chcemy, aby z tej strony mógł korzystać każdy, także za pomocą klawiatury, czytnika ekranu, powiększenia czy przy wolnym połączeniu. Dążymy do spełnienia wytycznych WCAG 2.2 na poziomie AA.</p>` },
  { h: 'Co zrobiliśmy', body: `<ul><li>Wszystkie funkcje działają z klawiatury, z wyraźnie widocznym fokusem.</li><li>Logiczna struktura nagłówków, czytelne punkty orientacyjne i link „przejdź do treści”.</li><li>Opisowe teksty alternatywne dla wszystkich zdjęć w portfolio.</li><li>Odpowiedni kontrast kolorów i tekst skalujący się z ustawieniami przeglądarki.</li><li>Pola formularza z etykietami i komunikatami o błędach odczytywanymi przez technologie wspomagające.</li><li>Jeśli system prosi o ograniczenie ruchu, animacje są wyłączone i od razu widzisz spokojny stan końcowy.</li><li>Lekkie strony bez narzędzi śledzących, które szybko ładują się nawet przy słabym połączeniu.</li></ul>` },
  { h: 'Znane ograniczenia', body: `<p>Opinie w Google zostały opublikowane po angielsku. Na stronie pokazuję oznaczone tłumaczenie, a pod nim oryginał. Oba teksty mają właściwy kod języka, więc czytniki ekranu używają poprawnej wymowy.</p>` },
  { h: 'Znalazłeś problem?', body: `<p>Coś nie działa? Daj nam znać: ${E} lub ${P}. Odpowiemy jak najszybciej, a w międzyczasie chętnie pomożemy w inny sposób.</p>` }
]}
}
};
