// Legal pages. Only facts that are known are stated; nothing is invented.
// Business registration data that is not yet verified (address, KvK, BTW) is intentionally not shown —
// see README “Required business data before live deployment”.
// GW Graphic Design is a sole proprietorship: the texts use “I / ik / ja” or neutral wording, never a corporate “we”.

import { SITE } from './content.mjs';
const KVK = (l, v) => SITE.kvk ? `<dt>${l}</dt><dd>${SITE.kvk}</dd>` : '';
const ADDR = l => SITE.address && SITE.address.street ? `<dt>${l}</dt><dd>${SITE.address.street}, ${SITE.address.postalCode} ${SITE.address.city}</dd>` : '';
const LEGALNAME = l => SITE.legalName ? `<dt>${l}</dt><dd>${SITE.legalName}</dd>` : '';
const BTW = (l) => SITE.btw ? `<dt>${l}</dt><dd>${SITE.btw}</dd>` : '';
const E = '<a href="mailto:design@gwgraphic.com">design@gwgraphic.com</a>';
const P = '<a href="tel:+31644319415">+31&nbsp;6&nbsp;44&nbsp;31&nbsp;94&nbsp;15</a>';
const AP_NL = '<a href="https://www.autoriteitpersoonsgegevens.nl" rel="noopener" target="_blank">Autoriteit Persoonsgegevens</a>';
const AP_EN = '<a href="https://www.autoriteitpersoonsgegevens.nl/en" rel="noopener" target="_blank">Dutch Data Protection Authority (Autoriteit Persoonsgegevens)</a>';
const AP_PL = '<a href="https://www.autoriteitpersoonsgegevens.nl/en" rel="noopener" target="_blank">holenderski organ ochrony danych (Autoriteit Persoonsgegevens)</a>';
// paragraphs → <p>…</p>
const ps = (...a) => a.map(x => `<p>${x}</p>`).join('');

export const LEGAL = {
/* =================================================================== PRIVACY */
privacy: {
nl: { title: 'Privacybeleid', description: 'Hoe GW Graphic Design omgaat met persoonsgegevens van klanten en websitebezoekers.',
  sections: [
  { h: 'Wie is verantwoordelijk?', body: `<p>GW Graphic Design, de eenmanszaak van Grzegorz Woźniak in Noord-Brabant, Nederland, is verwerkingsverantwoordelijke voor de persoonsgegevens die in dit privacybeleid worden beschreven.</p><p>Vragen over privacy of een verzoek over je gegevens? Mail naar ${E} of bel ${P}.</p>` },
  { h: 'Welke gegevens verwerk ik?', body: `<ul><li><strong>Contactgegevens</strong> die je mij zelf verstrekt: naam, bedrijfsnaam, e-mailadres en telefoonnummer.</li><li><strong>Projectinformatie</strong> die je mij stuurt: je bericht, de gekozen diensten en eventuele bestanden die je per e-mail of WhatsApp meestuurt.</li><li><strong>Klant- en opdrachtgegevens</strong>: offertes, afspraken, facturen en betalingen.</li><li><strong>Technische gegevens</strong>: bij het verzenden van het formulier wordt je IP-adres gehasht (onherkenbaar gemaakt) en maximaal één uur bewaard om misbruik te voorkomen. De hostingprovider houdt daarnaast standaard serverlogbestanden bij (zoals IP-adres, tijdstip en opgevraagde pagina) voor de beveiliging.</li></ul><p>Ik vraag niet om bijzondere persoonsgegevens en heb deze niet nodig voor je aanvraag of opdracht.</p>` },
  { h: 'Waarvoor en op welke grondslag?', body: `<div class="table-wrap"><table><thead><tr><th>Doel</th><th>Grondslag (AVG)</th></tr></thead><tbody>
<tr><td>Je aanvraag beantwoorden en een offerte maken</td><td>Maatregelen op jouw verzoek vóór een overeenkomst (art. 6 lid 1 b)</td></tr>
<tr><td>De opdracht uitvoeren en met je communiceren</td><td>Uitvoering van de overeenkomst (art. 6 lid 1 b)</td></tr>
<tr><td>Facturatie en boekhouding</td><td>Wettelijke verplichting (art. 6 lid 1 c)</td></tr>
<tr><td>Beveiliging van website en formulier, spam- en misbruikpreventie</td><td>Gerechtvaardigd belang (art. 6 lid 1 f)</td></tr>
<tr><td>Afgerond werk tonen in het portfolio</td><td>Gerechtvaardigd belang, of toestemming waar nodig; zie de algemene voorwaarden</td></tr>
</tbody></table></div>` },
  { h: 'Het offerteformulier', body: ps(`Wat je in het formulier invult, wordt via een beveiligde verbinding (HTTPS) naar de server gestuurd en als e-mail bij ${E} bezorgd. Ik gebruik deze gegevens alleen om je aanvraag te beantwoorden en, als je opdracht geeft, om die opdracht uit te voeren. Het formulier bevat geen trackers en je kunt er geen bestanden mee uploaden.`) },
  { h: 'Met wie deel ik gegevens?', body: `<p>Ik verkoop geen persoonsgegevens. Ik deel gegevens alleen wanneer en voor zover dat nodig is voor een specifiek doel:</p><ul><li>de <strong>hosting- en e-mailprovider</strong>, die de website en de mailbox technisch beheert;</li><li>een <strong>boekhouder of boekhoudsoftware</strong> voor facturen en de administratie;</li><li><strong>productiepartners of vervoerders</strong>, alleen als dat voor jouw opdracht nodig is (bijvoorbeeld een afleveradres).</li></ul><p>Met partijen die namens mij gegevens verwerken, maak ik afspraken over beveiliging en vertrouwelijkheid. Neem je via WhatsApp contact met mij op, dan verwerkt WhatsApp (Meta) je gegevens volgens de eigen voorwaarden en het privacybeleid van WhatsApp. Het bekijken van deze website activeert WhatsApp niet.</p>` },
  { h: 'Doorgifte buiten de EER', body: ps('Ik kies waar mogelijk dienstverleners die gegevens binnen de Europese Economische Ruimte verwerken. Verwerkt een dienstverlener gegevens buiten de EER, dan gebeurt dat alleen met een passende waarborg, zoals een adequaatheidsbesluit of de modelcontractbepalingen van de Europese Commissie.') },
  { h: 'Hoe lang bewaar ik gegevens?', body: `<ul><li>Aanvragen die niet tot een opdracht leiden: maximaal 12 maanden na het laatste contact.</li><li>Klant- en projectgegevens: zolang de samenwerking loopt en daarna zolang dat nodig is voor garantie of vragen over het geleverde werk.</li><li>Facturen en de administratie: 7 jaar, zoals de Nederlandse fiscale bewaarplicht voorschrijft.</li><li>Gehashte IP-adressen voor misbruikpreventie: maximaal 1 uur.</li></ul>` },
  { h: 'Beveiliging', body: ps('Ik neem passende technische en organisatorische maatregelen: een versleutelde verbinding (HTTPS), beveiligde serverinstellingen, beperkte toegang tot gegevens, back-ups en regelmatige updates. Het formulier is beschermd tegen spam en misbruik zonder tracking of CAPTCHA van derden.') },
  { h: 'Jouw rechten', body: ps(`Je hebt recht op inzage, rectificatie, verwijdering, beperking van de verwerking, bezwaar en overdraagbaarheid van je gegevens. Heb je toestemming gegeven, dan kun je die altijd intrekken; dat heeft geen gevolgen voor verwerking die al eerder plaatsvond. Stuur je verzoek naar ${E}. Ik reageer binnen één maand en kan je vragen je identiteit te bevestigen.`) },
  { h: 'Een klacht indienen', body: ps(`Heb je vragen of zorgen over de verwerking van je gegevens, neem dan eerst contact met mij op. Ik probeer de situatie te verduidelijken en een passende oplossing te vinden. Je hebt ook altijd het recht om een klacht in te dienen bij de ${AP_NL}.`) },
  { h: 'Cookies en externe diensten', body: `<p>Deze website gebruikt geen cookies voor statistieken, advertenties of tracking en laadt geen lettertypes, scripts of widgets van derden. Lees meer in het <a href="cookiebeleid.html">cookiebeleid</a>. Links naar Google, WhatsApp, Instagram, Facebook en LinkedIn openen pas een externe dienst als je erop klikt.</p>` },
  { h: 'Wijzigingen', body: ps('Dit privacybeleid wordt aangepast als de werking van de website, de gebruikte dienstverleners of de wet veranderen. Bovenaan deze pagina staat de datum van de laatste wijziging.') }
]},
en: { title: 'Privacy policy', description: 'How GW Graphic Design handles the personal data of clients and website visitors.',
  sections: [
  { h: 'Who is responsible?', body: `<p>GW Graphic Design, a sole proprietorship operated by Grzegorz Woźniak in North Brabant, the Netherlands, is the controller of the personal data described in this policy.</p><p>Questions about privacy or a request about your data? Email ${E} or call ${P}.</p>` },
  { h: 'What data do I process?', body: `<ul><li><strong>Contact details</strong> you provide to me: name, company name, email address and phone number.</li><li><strong>Project information</strong> you send to me: your message, the services you select and any files you send by email or WhatsApp.</li><li><strong>Client and order data</strong>: quotes, agreements, invoices and payments.</li><li><strong>Technical data</strong>: when you submit the form, your IP address is hashed (made unrecognisable) and kept for no more than one hour to prevent abuse. The hosting provider also keeps standard server log files (such as IP address, time and requested page) for security purposes.</li></ul><p>I do not ask for special categories of personal data and they are not needed to handle your enquiry or order.</p>` },
  { h: 'Purposes and legal bases', body: `<div class="table-wrap"><table><thead><tr><th>Purpose</th><th>Legal basis (GDPR)</th></tr></thead><tbody>
<tr><td>Answering your request and preparing a quote</td><td>Steps taken at your request before entering into a contract (Art. 6(1)(b))</td></tr>
<tr><td>Carrying out the order and communicating with you</td><td>Performance of a contract (Art. 6(1)(b))</td></tr>
<tr><td>Invoicing and accounting</td><td>Legal obligation (Art. 6(1)(c))</td></tr>
<tr><td>Security of the website and form, spam and abuse prevention</td><td>Legitimate interest (Art. 6(1)(f))</td></tr>
<tr><td>Showing completed work in the portfolio</td><td>Legitimate interest, or consent where required; see the terms and conditions</td></tr>
</tbody></table></div>` },
  { h: 'The quote form', body: ps(`What you enter in the form is sent over a secure connection (HTTPS) to the server and delivered as an email to ${E}. I only use this information to reply to your enquiry and, if you place an order, to carry it out. The form contains no trackers and cannot be used to upload files.`) },
  { h: 'Who do I share data with?', body: `<p>I do not sell personal data. I only share it where and to the extent necessary for a specific purpose:</p><ul><li>the <strong>hosting and email provider</strong> that runs the website and mailbox;</li><li>an <strong>accountant or accounting software</strong> for invoices and bookkeeping;</li><li><strong>production partners or carriers</strong>, only when your order requires it (for example a delivery address).</li></ul><p>I make arrangements on security and confidentiality with anyone who processes data on my behalf. If you contact me via WhatsApp, WhatsApp (Meta) processes your data under its own terms and privacy policy. Simply viewing this website does not activate WhatsApp.</p>` },
  { h: 'Transfers outside the EEA', body: ps('Where possible, I choose service providers that process data within the European Economic Area. If a provider processes data outside the EEA, this only happens with an appropriate safeguard, such as an adequacy decision or the European Commission’s standard contractual clauses.') },
  { h: 'How long do I keep data?', body: `<ul><li>Requests that do not lead to an order: no more than 12 months after the last contact.</li><li>Client and project data: for as long as we work together, and afterwards for as long as needed for warranty matters or questions about the delivered work.</li><li>Invoices and accounting records: 7 years, as required by Dutch tax law.</li><li>Hashed IP addresses for abuse prevention: no more than 1 hour.</li></ul>` },
  { h: 'Security', body: ps('I take appropriate technical and organisational measures: an encrypted connection (HTTPS), secure server settings, limited access to data, backups and regular updates. The form is protected against spam and abuse without third-party tracking or CAPTCHA.') },
  { h: 'Your rights', body: ps(`You have the right of access, rectification, erasure, restriction of processing, objection and data portability. If you have given consent, you can withdraw it at any time; this does not affect processing that took place before. Send your request to ${E}. I respond within one month and may ask you to confirm your identity.`) },
  { h: 'Making a complaint', body: ps(`If you have concerns about how your data is handled, please contact me first. I will try to clarify the issue and find a solution. You always have the right to lodge a complaint with the ${AP_EN}.`) },
  { h: 'Cookies and external services', body: `<p>This website does not use cookies for analytics, advertising or tracking, and does not load third-party fonts, scripts or widgets. Read more in the <a href="cookies.html">cookie policy</a>. Links to Google, WhatsApp, Instagram, Facebook and LinkedIn only open an external service when you click them.</p>` },
  { h: 'Changes', body: ps('I update this privacy policy when the way the website works, the service providers used or the law change. The date of the latest change is shown at the top of this page.') }
]},
pl: { title: 'Polityka prywatności', description: 'Jak GW Graphic Design przetwarza dane osobowe klientów i osób odwiedzających stronę.',
  sections: [
  { h: 'Kto jest administratorem danych?', body: `<p>Administratorem danych osobowych jest GW Graphic Design — działalność prowadzona przez Grzegorza Woźniaka w Brabancji Północnej w Holandii.</p><p>Masz pytanie o prywatność albo wniosek dotyczący Twoich danych? Napisz na ${E} lub zadzwoń: ${P}.</p>` },
  { h: 'Jakie dane przetwarzam?', body: `<ul><li><strong>Dane kontaktowe</strong>, które mi podajesz: imię i nazwisko, nazwa firmy, adres e-mail i numer telefonu.</li><li><strong>Informacje o projekcie</strong>, które mi przesyłasz: wiadomość, wybrane usługi i pliki wysłane e-mailem lub przez WhatsApp.</li><li><strong>Dane klientów i zleceń</strong>: wyceny, ustalenia, faktury i płatności.</li><li><strong>Dane techniczne</strong>: przy wysyłce formularza Twój adres IP jest haszowany (przekształcany w nierozpoznawalną postać) i przechowywany najwyżej godzinę, aby zapobiegać nadużyciom. Dostawca hostingu prowadzi też standardowe logi serwera (np. adres IP, czas, otwierana strona) ze względów bezpieczeństwa.</li></ul><p>Nie proszę o szczególne kategorie danych osobowych i nie są one potrzebne do realizacji zlecenia.</p>` },
  { h: 'Cele i podstawy prawne', body: `<div class="table-wrap"><table><thead><tr><th>Cel</th><th>Podstawa prawna (RODO)</th></tr></thead><tbody>
<tr><td>Odpowiedź na zapytanie i przygotowanie wyceny</td><td>Działania na Twoje żądanie przed zawarciem umowy (art. 6 ust. 1 lit. b)</td></tr>
<tr><td>Realizacja zlecenia i kontakt z Tobą</td><td>Wykonanie umowy (art. 6 ust. 1 lit. b)</td></tr>
<tr><td>Fakturowanie i księgowość</td><td>Obowiązek prawny (art. 6 ust. 1 lit. c)</td></tr>
<tr><td>Bezpieczeństwo strony i formularza, ochrona przed spamem i nadużyciami</td><td>Prawnie uzasadniony interes (art. 6 ust. 1 lit. f)</td></tr>
<tr><td>Pokazywanie zrealizowanych prac w portfolio</td><td>Prawnie uzasadniony interes lub zgoda, gdy jest wymagana; zob. regulamin</td></tr>
</tbody></table></div>` },
  { h: 'Formularz zapytania', body: ps(`Dane wpisane w formularzu są przesyłane przez bezpieczne połączenie HTTPS na serwer i dostarczane jako wiadomość e-mail na adres ${E}. Wykorzystuję je wyłącznie do odpowiedzi na zapytanie, a w przypadku zlecenia — do jego realizacji. Formularz nie zawiera narzędzi śledzących i nie służy do przesyłania plików.`) },
  { h: 'Komu przekazuję dane?', body: `<p>Nie sprzedaję danych osobowych. Przekazuję je wyłącznie wtedy i w takim zakresie, w jakim jest to potrzebne do realizacji określonego celu:</p><ul><li><strong>dostawcy hostingu i poczty e-mail</strong>, który technicznie obsługuje stronę i skrzynkę;</li><li><strong>księgowemu lub programowi księgowemu</strong> — w zakresie faktur i dokumentacji;</li><li><strong>partnerom produkcyjnym lub przewoźnikom</strong> — tylko wtedy, gdy wymaga tego Twoje zlecenie (np. adres dostawy).</li></ul><p>Z podmiotami, które przetwarzają dane w moim imieniu, uzgadniam zasady bezpieczeństwa i poufności. Jeśli kontaktujesz się ze mną przez WhatsApp, WhatsApp (Meta) przetwarza Twoje dane na podstawie własnego regulaminu i polityki prywatności. Samo przeglądanie tej strony nie uruchamia WhatsApp.</p>` },
  { h: 'Przekazywanie danych poza EOG', body: ps('W miarę możliwości wybieram usługodawców przetwarzających dane na terenie Europejskiego Obszaru Gospodarczego. Jeśli usługodawca przetwarza dane poza EOG, odbywa się to wyłącznie z odpowiednim zabezpieczeniem, np. na podstawie decyzji stwierdzającej odpowiedni stopień ochrony lub standardowych klauzul umownych Komisji Europejskiej.') },
  { h: 'Jak długo przechowuję dane?', body: `<ul><li>Zapytania, które nie prowadzą do zlecenia: najwyżej 12 miesięcy od ostatniego kontaktu.</li><li>Dane klientów i projektów: przez czas współpracy, a następnie tak długo, jak jest to potrzebne w związku z gwarancją lub pytaniami o wykonaną pracę.</li><li>Faktury i dokumentacja księgowa: 7 lat, zgodnie z holenderskim obowiązkiem podatkowym.</li><li>Haszowane adresy IP (ochrona przed nadużyciami): najwyżej 1 godzinę.</li></ul>` },
  { h: 'Bezpieczeństwo', body: ps('Stosuję odpowiednie środki techniczne i organizacyjne: szyfrowane połączenie (HTTPS), bezpieczną konfigurację serwera, ograniczony dostęp do danych, kopie zapasowe i regularne aktualizacje. Formularz jest chroniony przed spamem i nadużyciami bez śledzenia i bez zewnętrznej CAPTCHA.') },
  { h: 'Twoje prawa', body: ps(`Masz prawo dostępu do danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, sprzeciwu oraz przenoszenia danych. Jeśli wyraziłeś zgodę, możesz ją w każdej chwili wycofać; nie wpływa to na zgodność z prawem wcześniejszego przetwarzania. Wniosek dotyczący danych wyślij na ${E}. Odpowiadam w ciągu miesiąca i w razie potrzeby mogę poprosić o potwierdzenie tożsamości.`) },
  { h: 'Skarga', body: ps(`Jeżeli masz zastrzeżenia do sposobu przetwarzania danych, najpierw daj mi znać — spróbuję wyjaśnić sprawę i znaleźć rozwiązanie. Zawsze masz też prawo złożyć skargę do organu nadzorczego: ${AP_PL}.`) },
  { h: 'Cookies i usługi zewnętrzne', body: `<p>Ta strona nie używa cookies do statystyk, reklam ani śledzenia i nie wczytuje zewnętrznych czcionek, skryptów ani widżetów. Więcej w <a href="polityka-cookies.html">polityce cookies</a>. Linki do Google, WhatsApp, Instagrama, Facebooka i LinkedIn otwierają usługę zewnętrzną dopiero po kliknięciu.</p>` },
  { h: 'Zmiany', body: ps('Politykę aktualizuję, gdy zmienia się sposób działania strony, wykorzystywani usługodawcy lub obowiązujące przepisy. Data ostatniej zmiany znajduje się na górze strony.') }
]}
},

/* =================================================================== COOKIES */
cookies: {
nl: { title: 'Cookiebeleid', description: 'Welke cookies en opslag de website van GW Graphic Design gebruikt: geen tracking, geen advertenties, geen diensten van derden.',
  sections: [
  { h: 'Kort gezegd', body: `<p>Deze website plaatst <strong>geen cookies</strong> en gebruikt geen analytics, advertentienetwerken, social-media-pixels of andere trackers. Lettertypes, afbeeldingen en scripts worden allemaal vanaf de eigen server van de website geladen. Daarom is er ook geen cookiebanner: er is niets om toestemming voor te vragen.</p>` },
  { h: 'Wat wordt er wel opgeslagen?', body: `<div class="table-wrap"><table><thead><tr><th>Naam</th><th>Type</th><th>Doel</th><th>Bewaartermijn</th></tr></thead><tbody>
<tr><td><code>gwIntroVisits</code></td><td>localStorage</td><td>Telt je bezoeken (één per browsersessie), zodat vanaf het vierde bezoek de optie verschijnt om de openingsanimatie uit te zetten.</td><td>Tot je het wist via Cookie-instellingen of je browser</td></tr><tr><td><code>gwIntroDisabled</code></td><td>localStorage</td><td>Alleen als je zelf kiest voor ‘Animatie niet meer tonen’: onthoudt die keuze.</td><td>Tot je het wist of de animatie weer inschakelt</td></tr><tr><td><code>gwIntroSession</code></td><td>sessionStorage</td><td>Voorkomt dat de animatie binnen hetzelfde bezoek opnieuw start.</td><td>Tot je het tabblad sluit</td></tr>
</tbody></table></div><p>Dit zijn functionele voorkeuren: ze blijven op je eigen apparaat, worden niet naar GW Graphic Design verzonden, worden niet gebruikt voor statistieken of reclame en zijn niet tot jou als persoon te herleiden.</p>` },
  { h: 'Serverlogbestanden', body: `<p>De hostingprovider registreert standaard technische serverlogs (zoals IP-adres, tijdstip en opgevraagde pagina) om de website veilig en bereikbaar te houden. Daarbij worden geen cookies gebruikt. Meer hierover lees je in het <a href="privacybeleid.html">privacybeleid</a>.</p>` },
  { h: 'Externe links', body: ps('Links naar Google Reviews, WhatsApp, Instagram, Facebook en LinkedIn openen de betreffende dienst pas als je erop klikt. Vanaf dat moment gelden de cookie- en privacyregels van die dienst.') },
  { h: 'Je keuze beheren', body: ps('Via <strong>Cookie-instellingen</strong> onderaan elke pagina zie je dit overzicht en kun je de opgeslagen gegevens direct wissen. Je kunt de opslag ook altijd verwijderen via de instellingen van je browser.') },
  { h: 'Wijzigingen', body: ps('Als in de toekomst niet-noodzakelijke statistiek- of andere trackingtechnologieën worden gebruikt, wordt dit beleid vooraf aangepast. Als toestemming vereist is, krijg je vóór activering een even duidelijke mogelijkheid om toestemming te geven of te weigeren.') }
]},
en: { title: 'Cookie policy', description: 'Which cookies and storage the GW Graphic Design website uses: no tracking, no advertising, no third-party services.',
  sections: [
  { h: 'In short', body: `<p>This website sets <strong>no cookies</strong> and does not use analytics, advertising networks, social media pixels or other trackers. Fonts, images and scripts are all loaded from the website’s own server. That is why there is no cookie banner: there is no consent to ask for.</p>` },
  { h: 'What is stored?', body: `<div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Purpose</th><th>Retention</th></tr></thead><tbody>
<tr><td><code>gwIntroVisits</code></td><td>localStorage</td><td>Counts your visits (one per browser session), so that from the fourth visit you get the option to switch the opening animation off.</td><td>Until you clear it via Cookie settings or your browser</td></tr><tr><td><code>gwIntroDisabled</code></td><td>localStorage</td><td>Only if you choose ‘Don’t show again’ yourself: remembers that choice.</td><td>Until you clear it or switch the animation back on</td></tr><tr><td><code>gwIntroSession</code></td><td>sessionStorage</td><td>Prevents the animation from starting again during the same visit.</td><td>Until you close the tab</td></tr>
</tbody></table></div><p>These are functional preferences. They stay on your device and are not sent to GW Graphic Design. They are not used for statistics or advertising and cannot identify you.</p>` },
  { h: 'Server log files', body: `<p>The hosting provider records standard technical server logs (such as IP address, time and requested page) to keep the website secure and available. No cookies are involved. Read more in the <a href="privacy.html">privacy policy</a>.</p>` },
  { h: 'External links', body: ps('Links to Google Reviews, WhatsApp, Instagram, Facebook and LinkedIn only open that service when you click them. From then on, that service’s own cookie and privacy rules apply.') },
  { h: 'Managing your choice', body: ps('Use <strong>Cookie settings</strong> at the bottom of every page to see this overview and clear stored data straight away. You can also delete this data at any time in your browser settings.') },
  { h: 'Changes', body: ps('If non-essential analytics or similar technologies are introduced in the future, this policy will be updated first. Where consent is required, an equally accessible option to accept or refuse will be provided before those technologies are activated.') }
]},
pl: { title: 'Polityka cookies', description: 'Jakich plików cookies i pamięci używa strona GW Graphic Design: bez śledzenia, bez reklam, bez usług zewnętrznych.',
  sections: [
  { h: 'W skrócie', body: `<p>Ta strona <strong>nie zapisuje plików cookies</strong> i nie używa narzędzi analitycznych, sieci reklamowych, pikseli mediów społecznościowych ani innych narzędzi śledzących. Czcionki, zdjęcia i skrypty są ładowane z serwera tej strony. Dlatego strona nie wyświetla banera cookies — nie ma zgody, o którą trzeba byłoby prosić.</p>` },
  { h: 'Co jest zapisywane?', body: `<div class="table-wrap"><table><thead><tr><th>Nazwa</th><th>Rodzaj</th><th>Cel</th><th>Okres przechowywania</th></tr></thead><tbody>
<tr><td><code>gwIntroVisits</code></td><td>localStorage</td><td>Liczy wizyty (jedna na sesję przeglądarki), żeby od czwartej wizyty pokazać opcję wyłączenia animacji otwarcia.</td><td>Do usunięcia w Ustawieniach cookies lub w przeglądarce</td></tr><tr><td><code>gwIntroDisabled</code></td><td>localStorage</td><td>Tylko jeśli sam wybierzesz „Nie pokazuj ponownie”: zapamiętuje ten wybór.</td><td>Do usunięcia lub ponownego włączenia animacji</td></tr><tr><td><code>gwIntroSession</code></td><td>sessionStorage</td><td>Zapobiega ponownemu uruchomieniu animacji w trakcie tej samej wizyty.</td><td>Do zamknięcia karty</td></tr>
</tbody></table></div><p>To funkcjonalne preferencje: zostają na Twoim urządzeniu, nie są przesyłane do GW Graphic Design, nie służą do statystyk ani reklam i nie pozwalają Cię zidentyfikować.</p>` },
  { h: 'Logi serwera', body: `<p>Dostawca hostingu rejestruje dane techniczne zapytań do serwera (np. adres IP, czas i otwieraną stronę), tak jak w przypadku każdej strony internetowej. Służy to bezpieczeństwu i dostępności strony i odbywa się bez cookies. Więcej w <a href="polityka-prywatnosci.html">polityce prywatności</a>.</p>` },
  { h: 'Linki zewnętrzne', body: ps('Linki do opinii Google, WhatsApp, Instagrama, Facebooka i LinkedIn otwierają daną usługę dopiero po kliknięciu. Od tej chwili obowiązują zasady cookies i prywatności tej usługi.') },
  { h: 'Zarządzanie wyborem', body: ps('W <strong>Ustawieniach cookies</strong> na dole każdej strony zobaczysz to zestawienie i od razu wyczyścisz zapisane dane. Możesz je też w każdej chwili usunąć w ustawieniach przeglądarki.') },
  { h: 'Zmiany', body: ps('Jeśli w przyszłości strona zacznie korzystać ze statystyk lub innych nieniezbędnych technologii, polityka zostanie zaktualizowana, a jeśli przepisy będą tego wymagały, przed uruchomieniem takich technologii pojawi się możliwość wyrażenia lub odmowy zgody.') }
]}
},

/* =================================================================== TERMS */
terms: {
nl: { title: 'Algemene voorwaarden', description: 'De algemene voorwaarden van GW Graphic Design voor grafisch ontwerp, drukwerk, kleding, belettering, websites en montage.',
  sections: [
  { h: 'Toepassing', body: ps('Deze voorwaarden gelden voor alle offertes, opdrachten en leveringen van GW Graphic Design (Grzegorz Woźniak), tenzij in de offerte of een schriftelijke overeenkomst iets anders is afgesproken.', 'Ze hebben onder meer betrekking op grafisch ontwerp, logo en visuele identiteit, drukwerk, bedrijfskleding, signing, voertuigbelettering, raambelettering, websites, promotionele producten en montage.') },
  { h: 'Offertes en opdrachten', body: ps('Een offerte is gebaseerd op de informatie die op het moment van opstellen bekend is en blijft 30 dagen geldig, tenzij anders vermeld.', 'Een opdracht komt tot stand zodra je de offerte schriftelijk accepteert, ook per e-mail of WhatsApp.', 'Wijzigingen of werkzaamheden buiten de afgesproken omvang bespreek ik vooraf. Meerwerk kan apart worden geoffreerd.') },
  { h: 'Aanbetaling en betaling', body: ps('Nadat de omvang van de opdracht is vastgesteld, vraag ik een aanbetaling van minimaal 50% van het totale orderbedrag, tenzij in de offerte iets anders is afgesproken.', 'Het resterende bedrag wordt betaald na goedkeuring van het ontwerp en vóór de start van drukwerk of productie.', 'Omvat de opdracht geen drukwerk of productie, dan staat de betalingstermijn voor het resterende bedrag in de offerte of op de factuur.', 'Facturen moeten binnen de vermelde betalingstermijn worden voldaan. Zolang een opeisbare betaling openstaat, kan ik productie, levering van definitieve bestanden of montage uitstellen.') },
  { h: 'Aangeleverd materiaal', body: ps('Je bent verantwoordelijk voor de juistheid van teksten, namen, contactgegevens, afmetingen en andere materialen die je aanlevert. Daarbij bevestig je dat je het recht hebt deze materialen te gebruiken.', 'Ik neem geen opdrachten aan met onrechtmatige inhoud of materiaal dat rechten van anderen schendt.') },
  { h: 'Ontwerp en akkoord', body: ps('Voordat een ontwerp in productie gaat, ontvang je een versie ter controle.', 'Controleer spelling, cijfers, kleuren, afmetingen en plaatsing zorgvuldig.', 'Na jouw akkoord gaat het ontwerp in productie.', 'Was een fout zichtbaar in het goedgekeurde ontwerp, dan ligt de verantwoordelijkheid voor de goedkeuring daarvan bij de klant. Ontstaat een fout aan mijn kant tijdens de productie of uitvoering, dan herstel ik die.') },
  { h: 'Correctierondes', body: ps('Het aantal ontwerpvoorstellen en correctierondes dat in de prijs is inbegrepen, staat in de offerte.', 'Extra correctierondes, een nieuwe richting of aanvullende onderdelen bespreek ik vooraf en kunnen apart worden berekend.') },
  { h: 'Kleur, materiaal en toleranties', body: ps('Kleuren op een beeldscherm kunnen afwijken van kleuren op papier, textiel of folie.', 'Kleine verschillen in kleur, snijwerk, plaatsing, bedrukking, materiaalpartij of afmetingen binnen normale productietoleranties worden niet als gebrek beschouwd.', 'Heeft een specifiek materiaal relevante beperkingen, dan bespreek ik die vóór de productie.') },
  { h: 'Voertuigbelettering en montage', body: ps('Meld mij vóór de montage eventuele schade, overgespoten delen, coatings, eerdere reparaties of andere bijzonderheden van de ondergrond.', 'De hechting en latere verwijdering van folie zijn onder meer afhankelijk van de staat en leeftijd van lak of glas, eerdere reparaties, temperatuur en het type ondergrond.', 'Het voertuig of de ruit moet op het afgesproken tijdstip schoon en toegankelijk zijn. Eventuele specifieke risico’s bespreek ik vóór de montage met je.') },
  { h: 'Websites', body: ps('Een website omvat de functies en inhoud die in de offerte zijn opgenomen.', 'Hosting, domeinnaam, betaalde plug-ins, licenties van derden, onderhoud, teksten en updates zijn alleen inbegrepen wanneer dit uitdrukkelijk is afgesproken.', 'Na oplevering ben je zelf verantwoordelijk voor updates, back-ups en beveiliging, tenzij een aparte onderhoudsovereenkomst anders bepaalt.') },
  { h: 'Intellectueel eigendom', body: ps('Schetsen, niet gekozen voorstellen en werkbestanden blijven eigendom van GW Graphic Design, tenzij anders afgesproken.', 'Na volledige betaling krijg je het recht om het definitieve ontwerp te gebruiken binnen de omvang die in de offerte is omschreven.', 'Lettertypes, beeldmateriaal, plug-ins, software en andere materialen van derden vallen onder hun eigen licentievoorwaarden.') },
  { h: 'Portfolio', body: ps('Als ik niet vooraf vertrouwelijkheid met je heb afgesproken, mag ik opgeleverd werk dat publiek zichtbaar is tonen in het portfolio en op de sociale media van GW Graphic Design.', 'Wil je niet dat een specifieke opdracht wordt gepubliceerd, laat mij dit dan vóór publicatie schriftelijk weten.') },
  { h: 'Planning', body: ps('Opgegeven termijnen zijn schattingen en zijn onder meer afhankelijk van tijdige goedkeuring, betaling, beschikbaarheid van materialen en productie door derden.', 'Bij vertraging buiten mijn invloed laat ik je zo snel mogelijk weten wat de aangepaste planning is.') },
  { h: 'Annulering', body: ps('Annuleer je een opdracht nadat het werk is gestart, dan worden het reeds uitgevoerde werk en de kosten die al onherroepelijk bij derden zijn gemaakt in rekening gebracht.', 'Voor consumenten blijven de wettelijke rechten gelden. Maatwerk en gepersonaliseerde producten kunnen, voor zover de wet dat bepaalt, zijn uitgezonderd van het herroepingsrecht.') },
  { h: 'Klachten', body: ps('Meld zichtbare gebreken of ontbrekende onderdelen zo snel mogelijk na levering, bij voorkeur met foto’s.', 'Ik beoordeel het probleem en stel vervolgens een passende oplossing voor.', 'Dit doet geen afbreuk aan je wettelijke rechten.') },
  { h: 'Aansprakelijkheid', body: ps('Voor zover de wet dit toestaat, is GW Graphic Design niet aansprakelijk voor indirecte schade of gederfde winst en is de aansprakelijkheid beperkt tot het factuurbedrag van de betreffende opdracht.', 'Deze beperking geldt niet bij opzet, grove nalatigheid of wanneer de wet een beperking van aansprakelijkheid niet toestaat.') },
  { h: 'Consumenten', body: ps('Ben je consument, dan gaan dwingende regels van consumentenrecht voor op bepalingen in deze voorwaarden die daarmee in strijd zijn.') },
  { h: 'Toepasselijk recht', body: ps('Op alle opdrachten is Nederlands recht van toepassing.', 'Bij een geschil probeer ik eerst samen met jou tot een oplossing te komen voordat de zaak aan de bevoegde rechter wordt voorgelegd.') }
]},
en: { title: 'Terms and conditions', description: 'The terms and conditions of GW Graphic Design for graphic design, print, apparel, vehicle graphics, websites and installation.',
  sections: [
  { h: 'Scope', body: ps('These terms apply to all quotes, orders and deliveries provided by GW Graphic Design (Grzegorz Woźniak), unless a quote or written agreement states otherwise. They cover, among other things, graphic design, logos and visual identity, print, branded clothing, signage, vehicle graphics, window graphics, websites, promotional products and installation.') },
  { h: 'Quotes and orders', body: ps('A quote is based on the information available when it is prepared and is valid for 30 days unless stated otherwise.', 'An order is accepted once you approve the quote in writing, including by email or WhatsApp.', 'I discuss any changes or work outside the agreed scope before carrying them out, and additional work may be quoted separately.') },
  { h: 'Deposit and payment', body: ps('Once the scope of the order has been agreed, I require a deposit of at least 50% of the total order value unless the quote states otherwise.', 'The remaining balance is due after the design has been approved and before printing or production begins.', 'If an order does not include printing or production, the due date for the remaining balance is stated in the quote or invoice.', 'Invoices must be paid by the due date shown on the invoice. I may pause production, delivery of final files or installation while a due payment remains outstanding.') },
  { h: 'Materials you provide', body: ps('You are responsible for the accuracy of any text, names, contact details, dimensions and other materials you provide, and you confirm that you have the right to use them.', 'I do not accept work containing unlawful content or material that infringes the rights of others.') },
  { h: 'Proof and approval', body: ps('Before a design goes into production, you will receive a version to review.', 'Please check spelling, numbers, colours, dimensions and placement carefully.', 'Once approved, the design goes into production.', 'If an error was visible in the approved design, responsibility for approving it rests with the client. If an error is introduced on my side during production or execution, I will correct it.') },
  { h: 'Revisions', body: ps('The number of design proposals and revision rounds included in the price is stated in the quote.', 'Additional revision rounds, a change of direction or new elements are discussed before the work is carried out and may be quoted separately.') },
  { h: 'Colour, materials and tolerances', body: ps('Colours displayed on a screen may differ from colours on paper, fabric or vinyl.', 'Small variations in colour, cutting, placement, print, material batch or dimensions that fall within normal production tolerances are not considered defects.', 'If a particular material has relevant limitations, I will explain them before production.') },
  { h: 'Vehicle graphics and installation', body: ps('Before installation, tell me about any damage, resprayed panels, coatings, previous repairs or other relevant characteristics of the surface.', 'Adhesion and later removal of vinyl depend on factors including the condition and age of the paint or glass, previous repairs, temperature and the type of surface.', 'The vehicle or window must be clean and accessible at the agreed time. I will discuss any specific risks with you before installation.') },
  { h: 'Websites', body: ps('A website includes the functions and content stated in the quote.', 'Hosting, domain registration, paid plugins, third-party licences, maintenance, copywriting and updates are included only when explicitly agreed.', 'After handover, you are responsible for updates, backups and security unless a separate maintenance agreement states otherwise.') },
  { h: 'Intellectual property', body: ps('Sketches, unused concepts and working files remain the property of GW Graphic Design unless agreed otherwise.', 'Once full payment has been received, you receive the right to use the final design within the scope described in the quote.', 'Fonts, images, plugins, software and other third-party materials remain subject to their own licences.') },
  { h: 'Portfolio', body: ps('Unless I have agreed confidentiality with you in advance, I may show completed work that is publicly visible in the GW Graphic Design portfolio and on social media.', 'If you do not want a particular project to be published, please let me know in writing before publication.') },
  { h: 'Delivery times', body: ps('Stated delivery times are estimates and depend on factors including timely approval, payment, material availability and production by third parties.', 'If a delay occurs for reasons outside my control, I will let you know about the revised timing as soon as possible.') },
  { h: 'Cancellation', body: ps('If you cancel an order after work has started, you are responsible for the work already completed and any costs that have already been irrevocably incurred with third parties.', 'Consumers retain their statutory rights. Custom-made or personalised products may be excluded from the right of withdrawal where permitted by law.') },
  { h: 'Complaints', body: ps('Please report visible defects or missing items as soon as reasonably possible after delivery, preferably with photos.', 'I will review the issue first and propose an appropriate solution.', 'This does not limit any statutory rights available to you.') },
  { h: 'Liability', body: ps('To the extent permitted by law, GW Graphic Design is not liable for indirect loss or loss of profit, and liability is limited to the invoice amount for the order concerned.', 'This limitation does not apply in cases of intent, gross negligence or where liability cannot legally be limited.') },
  { h: 'Consumers', body: ps('If you are a consumer, mandatory consumer protection law takes precedence over any provision of these terms that conflicts with it.') },
  { h: 'Governing law', body: ps('Dutch law applies to all orders.', 'If a dispute arises, I will first try to resolve it with you amicably before the matter is referred to the competent court.') }
]},
pl: { title: 'Regulamin', description: 'Ogólne warunki współpracy z GW Graphic Design: projektowanie, druk, odzież, oklejanie aut, strony internetowe i montaż.',
  sections: [
  { h: 'Zakres', body: ps('Niniejsze warunki dotyczą wszystkich wycen, zleceń i dostaw realizowanych przez GW Graphic Design (Grzegorz Woźniak), chyba że wycena lub pisemna umowa stanowi inaczej. Obejmują m.in. projektowanie graficzne, logo i identyfikację wizualną, druk, nadruki na odzieży, tablice i oznakowanie, oklejanie i grafikę na pojazdach, oklejanie szyb i witryn, strony internetowe, gadżety reklamowe oraz montaż.') },
  { h: 'Wyceny i zlecenia', body: ps('Wycena opiera się na informacjach znanych w chwili jej przygotowania i jest ważna przez 30 dni, chyba że wskazano inaczej. Zlecenie zostaje przyjęte z chwilą pisemnej akceptacji wyceny, także e-mailem lub przez WhatsApp. Zmiany lub prace wykraczające poza ustalony zakres omawiam przed ich wykonaniem i mogą zostać wycenione osobno.') },
  { h: 'Zaliczka i płatność', body: ps('Po ustaleniu zakresu zlecenia pobieram zaliczkę w wysokości co najmniej 50% całkowitej wartości zamówienia, chyba że w wycenie ustalono inaczej.', 'Pozostała kwota jest płatna po akceptacji projektu, przed rozpoczęciem druku lub produkcji.', 'Jeżeli zlecenie nie obejmuje druku ani produkcji, termin pozostałej płatności określa wycena lub faktura.', 'Faktury należy opłacić w terminie wskazanym na fakturze. Do czasu uregulowania wymagalnej płatności mogę wstrzymać produkcję, przekazanie plików końcowych lub montaż.') },
  { h: 'Materiały od klienta', body: ps('Odpowiadasz za poprawność przekazanych tekstów, nazw, danych kontaktowych, wymiarów i innych materiałów oraz potwierdzasz, że masz prawo do ich wykorzystania.', 'Nie przyjmuję do realizacji treści niezgodnych z prawem ani naruszających prawa innych osób.') },
  { h: 'Projekt do akceptacji', body: ps('Zanim projekt trafi do produkcji, otrzymasz wersję do sprawdzenia. Dokładnie zweryfikuj pisownię, liczby, kolory, wymiary i rozmieszczenie elementów.', 'Po akceptacji projekt trafia do produkcji.', 'Jeżeli błąd był widoczny w zaakceptowanym projekcie, odpowiedzialność za jego przeoczenie leży po stronie klienta. Jeżeli błąd powstanie po mojej stronie na etapie wykonania, poprawiam go.') },
  { h: 'Poprawki', body: ps('Liczba propozycji projektowych i rund poprawek wliczonych w cenę jest określona w wycenie.', 'Dodatkowe rundy poprawek, zmiana kierunku projektu lub nowe elementy omawiam przed ich wykonaniem i mogą zostać wycenione osobno.') },
  { h: 'Kolory, materiały i tolerancje', body: ps('Kolory widoczne na ekranie mogą różnić się od kolorów na papierze, tkaninie lub folii.', 'Niewielkie różnice w kolorze, cięciu, rozmieszczeniu, nadruku, partii materiału lub wymiarach, mieszczące się w standardowych tolerancjach produkcyjnych, nie są traktowane jako wada.', 'Jeżeli konkretny materiał ma istotne ograniczenia, informuję o nich przed realizacją.') },
  { h: 'Oklejanie i montaż', body: ps('Przed montażem poinformuj mnie o uszkodzeniach, ponownie lakierowanych elementach, powłokach, wcześniejszych naprawach lub innych szczególnych cechach powierzchni.', 'Przyczepność folii i możliwość jej późniejszego usunięcia zależą m.in. od stanu i wieku lakieru lub szkła, wcześniejszych napraw, temperatury oraz rodzaju podłoża.', 'Pojazd lub szyba muszą być czyste i dostępne w umówionym terminie. Ewentualne szczególne ryzyka omawiam z Tobą przed montażem.') },
  { h: 'Strony internetowe', body: ps('Strona internetowa obejmuje funkcje i treści wskazane w wycenie.', 'Hosting, domena, płatne wtyczki, licencje zewnętrzne, utrzymanie, teksty i aktualizacje są wliczone tylko wtedy, gdy zostało to wyraźnie uzgodnione.', 'Po przekazaniu strony odpowiadasz za jej aktualizacje, kopie zapasowe i bezpieczeństwo, chyba że osobna umowa serwisowa stanowi inaczej.') },
  { h: 'Prawa autorskie', body: ps('Szkice, niewybrane propozycje i pliki robocze pozostają własnością GW Graphic Design, chyba że ustalono inaczej.', 'Po pełnej zapłacie otrzymujesz prawa do korzystania z ostatecznego projektu w zakresie określonym w wycenie.', 'Czcionki, zdjęcia, wtyczki, oprogramowanie i inne materiały podmiotów trzecich podlegają ich własnym licencjom.') },
  { h: 'Portfolio', body: ps('Jeżeli wcześniej nie uzgodniłem z Tobą poufności, mogę prezentować publicznie widoczne, zrealizowane prace w portfolio oraz w mediach społecznościowych GW Graphic Design.', 'Jeżeli nie chcesz, aby dana realizacja była publikowana, poinformuj mnie o tym na piśmie przed publikacją.') },
  { h: 'Terminy realizacji', body: ps('Podane terminy są szacunkowe i zależą m.in. od terminowej akceptacji, płatności, dostępności materiałów oraz produkcji u podwykonawców.', 'W przypadku opóźnienia niezależnego ode mnie przekażę informację o zmianie terminu tak szybko, jak będzie to możliwe.') },
  { h: 'Rezygnacja', body: ps('Jeżeli zrezygnujesz ze zlecenia po rozpoczęciu prac, rozliczeniu podlega praca już wykonana oraz koszty, które zostały nieodwołalnie poniesione u podmiotów trzecich.', 'Konsumentom przysługują prawa wynikające z obowiązujących przepisów. Produkty wykonywane na zamówienie lub personalizowane mogą być wyłączone z prawa odstąpienia w zakresie przewidzianym przez prawo.') },
  { h: 'Reklamacje', body: ps('Widoczne wady lub braki zgłoś możliwie szybko po dostawie, najlepiej dołączając zdjęcia.', 'W pierwszej kolejności sprawdzę problem i zaproponuję odpowiednie rozwiązanie.', 'Nie ogranicza to praw przysługujących Ci na podstawie obowiązujących przepisów.') },
  { h: 'Odpowiedzialność', body: ps('W zakresie dozwolonym przez prawo GW Graphic Design nie odpowiada za szkody pośrednie ani utracone korzyści, a odpowiedzialność jest ograniczona do kwoty faktury dotyczącej danego zlecenia.', 'Ograniczenie to nie dotyczy winy umyślnej, rażącego niedbalstwa ani sytuacji, w których prawo nie pozwala na ograniczenie odpowiedzialności.') },
  { h: 'Konsumenci', body: ps('Jeżeli jesteś konsumentem, bezwzględnie obowiązujące przepisy prawa konsumenckiego mają pierwszeństwo przed postanowieniami niniejszego regulaminu, które byłyby z nimi sprzeczne.') },
  { h: 'Prawo właściwe', body: ps('Do wszystkich zleceń stosuje się prawo holenderskie.', 'W razie sporu w pierwszej kolejności spróbuję znaleźć z Tobą rozwiązanie polubowne, zanim sprawa zostanie skierowana do właściwego sądu.') }
]}
},

/* =================================================================== LEGAL NOTICE */
notice: {
nl: { title: 'Colofon', description: 'Bedrijfsgegevens en colofon van GW Graphic Design, studio voor grafisch ontwerp, reclame en belettering.',
  sections: [
  { h: 'Bedrijfsgegevens', body: `<dl><dt>Handelsnaam</dt><dd>GW Graphic Design</dd>${LEGALNAME('Statutaire naam')}<dt>Eigenaar</dt><dd>Grzegorz Woźniak</dd>${ADDR('Adres')}${KVK('KvK-nummer')}${BTW('Btw-id')}<dt>Regio</dt><dd>Noord-Brabant, Nederland</dd><dt>E-mail</dt><dd>${E}</dd><dt>Telefoon</dt><dd>${P}</dd><dt>Website</dt><dd><a href="https://www.gwgraphic.com/">www.gwgraphic.com</a></dd></dl>` },
  { h: 'Werkgebied', body: ps('Ontwerp en productie worden uitgevoerd voor klanten in Nederland, België, Duitsland en Polen. Montage op locatie wordt vooraf afgestemd op de locatie en de omvang van de werkzaamheden.') },
  { h: 'Ontwerp en uitvoering', body: ps('Ontwerp en inhoud van deze website: GW Graphic Design.<br>Lettertype: Archivo (SIL Open Font License), lokaal gehost.') },
  { h: 'Auteursrecht', body: ps('Het ontwerp van deze website, het logo van GW Graphic Design en de presentatie van het portfolio zijn auteursrechtelijk beschermd. Logo’s en merken van klanten blijven eigendom van hun respectieve eigenaren en worden uitsluitend getoond als voorbeelden van uitgevoerd werk.') },
  { h: 'Externe links', body: ps('Links naar externe websites worden voor het gemak aangeboden. GW Graphic Design is niet verantwoordelijk voor de inhoud, voorwaarden of privacypraktijken van externe websites.') }
]},
en: { title: 'Legal notice', description: 'Business details and legal notice of GW Graphic Design, graphic design, advertising and vehicle graphics studio.',
  sections: [
  { h: 'Business details', body: `<dl><dt>Trading name</dt><dd>GW Graphic Design</dd>${LEGALNAME('Registered name')}<dt>Owner</dt><dd>Grzegorz Woźniak</dd>${ADDR('Address')}${KVK('Chamber of Commerce (KvK)')}${BTW('VAT ID')}<dt>Region</dt><dd>North Brabant, the Netherlands</dd><dt>Email</dt><dd>${E}</dd><dt>Phone</dt><dd>${P}</dd><dt>Website</dt><dd><a href="https://www.gwgraphic.com/">www.gwgraphic.com</a></dd></dl>` },
  { h: 'Area of operation', body: ps('Design and production services are provided for clients in the Netherlands, Belgium, Germany and Poland. On-site installation is arranged in advance according to the location and scope of work.') },
  { h: 'Design and production', body: ps('Website design and content: GW Graphic Design.<br>Typeface: Archivo (SIL Open Font License), hosted locally.') },
  { h: 'Copyright', body: ps('The design of this website, the GW Graphic Design logo and the presentation of the portfolio are protected by copyright. Client logos and trademarks remain the property of their respective owners and are shown solely as examples of completed work.') },
  { h: 'External links', body: ps('External links are provided for convenience. GW Graphic Design is not responsible for the content, terms or privacy practices of external websites.') }
]},
pl: { title: 'Nota prawna', description: 'Dane firmy i nota prawna GW Graphic Design, studia projektowania graficznego, reklamy i oklejania.',
  sections: [
  { h: 'Dane firmy', body: `<dl><dt>Nazwa handlowa</dt><dd>GW Graphic Design</dd>${LEGALNAME('Pełna nazwa firmy')}<dt>Właściciel</dt><dd>Grzegorz Woźniak</dd>${ADDR('Adres')}${KVK('Numer KvK')}${BTW('Numer VAT (BTW)')}<dt>Region</dt><dd>Brabancja Północna, Holandia</dd><dt>E-mail</dt><dd>${E}</dd><dt>Telefon</dt><dd>${P}</dd><dt>Strona</dt><dd><a href="https://www.gwgraphic.com/">www.gwgraphic.com</a></dd></dl>` },
  { h: 'Obszar działania', body: ps('Projekt i produkcja dla klientów z Holandii, Belgii, Niemiec i Polski. Montaż oklejeń realizuję na miejscu, po wcześniejszym ustaleniu lokalizacji i zakresu prac.') },
  { h: 'Projekt i wykonanie', body: ps('Projekt i treści tej strony: GW Graphic Design.<br>Krój pisma: Archivo (SIL Open Font License), hostowany lokalnie.') },
  { h: 'Prawa autorskie', body: ps('Projekt strony, logo GW Graphic Design oraz prezentacja portfolio są chronione prawem autorskim. Logotypy i znaki klientów pozostają własnością ich właścicieli i są prezentowane wyłącznie jako przykłady zrealizowanych prac.') },
  { h: 'Linki zewnętrzne', body: ps('Linki do stron zewnętrznych są zamieszczane dla wygody użytkownika. GW Graphic Design nie odpowiada za treści, regulaminy ani zasady prywatności obowiązujące na tych stronach.') }
]}
},

/* =================================================================== ACCESSIBILITY */
a11y: {
nl: { title: 'Toegankelijkheid', description: 'Hoe de website van GW Graphic Design toegankelijk is gemaakt en hoe je een probleem kunt melden.',
  sections: [
  { h: 'Toegankelijkheid', body: ps('Ik vind het belangrijk dat deze website ook goed te gebruiken is met een toetsenbord, screenreader, browserzoom en bij een tragere internetverbinding. Bij de ontwikkeling wordt rekening gehouden met de WCAG 2.2-richtlijnen op niveau AA.') },
  { h: 'Wat is toegepast', body: `<ul><li>Alle functies werken met het toetsenbord, met een duidelijk zichtbare focus.</li><li>Een logische kopstructuur, herkenbare oriëntatiepunten en een link om direct naar de inhoud te gaan.</li><li>Beschrijvende alternatieve teksten bij alle portfoliofoto’s.</li><li>Voldoende kleurcontrast en tekst die meeschaalt met je browserinstellingen.</li><li>Formuliervelden met labels en foutmeldingen die door hulpsoftware worden voorgelezen.</li><li>Vraagt je besturingssysteem om minder beweging, dan worden animaties uitgeschakeld en zie je meteen de rustige eindstand.</li><li>Lichte pagina’s zonder trackers, zodat de site ook op een trage verbinding snel laadt.</li></ul>` },
  { h: 'Bekende beperkingen', body: ps('De Google-reviews zijn in het Engels gepubliceerd. Op deze pagina staat een Nederlandse vertaling, duidelijk gemarkeerd, met het origineel eronder. Beide teksten hebben de juiste taalcode, zodat schermlezers de juiste uitspraak gebruiken.') },
  { h: 'Een probleem gevonden?', body: ps(`Werkt iets niet zoals verwacht? Mail mij via ${E} of bel ${P}. Ik reageer zo snel mogelijk en help je indien nodig om de betreffende informatie op een andere manier te bereiken.`) }
]},
en: { title: 'Accessibility', description: 'How the GW Graphic Design website has been made accessible and how to report a problem.',
  sections: [
  { h: 'Accessibility approach', body: ps('I want this website to remain usable with a keyboard, screen reader, browser zoom and on slower connections. The site is developed with WCAG 2.2 Level AA guidelines in mind.') },
  { h: 'What has been implemented', body: `<ul><li>All features work with the keyboard, with a clearly visible focus.</li><li>A logical heading structure, recognisable landmarks and a link to skip straight to the content.</li><li>Descriptive alternative text for every portfolio photo.</li><li>Sufficient colour contrast and text that scales with your browser settings.</li><li>Form fields with labels and error messages that are announced by assistive technology.</li><li>If your operating system asks for reduced motion, animations are switched off and you see the final, static state straight away.</li><li>Lightweight pages without trackers, so the site loads quickly even on a slow connection.</li></ul>` },
  { h: 'Known limitations', body: ps('The Google reviews are shown in the language in which clients wrote them (English). They are marked with the correct language code so that screen readers use the right pronunciation.') },
  { h: 'Found a problem?', body: ps(`If something is not working as expected, email me at ${E} or call ${P}. I will respond as soon as reasonably possible and, where needed, help you access the information in another way.`) }
]},
pl: { title: 'Dostępność', description: 'Dostępność strony GW Graphic Design i sposób zgłaszania problemów.',
  sections: [
  { h: 'Założenia dostępności', body: ps('Zależy mi, aby z tej strony można było wygodnie korzystać również za pomocą klawiatury, czytnika ekranu, powiększenia oraz przy wolniejszym połączeniu. Strona jest rozwijana z uwzględnieniem wytycznych WCAG 2.2 na poziomie AA.') },
  { h: 'Co zostało wdrożone', body: `<ul><li>Wszystkie funkcje działają z klawiatury, a zaznaczenie (fokus) jest wyraźnie widoczne.</li><li>Logiczna struktura nagłówków, czytelne punkty orientacyjne i link „Przejdź do treści”.</li><li>Opisowe teksty alternatywne dla wszystkich zdjęć w portfolio.</li><li>Odpowiedni kontrast kolorów i tekst, który skaluje się razem z ustawieniami przeglądarki.</li><li>Pola formularza z etykietami i komunikatami o błędach odczytywanymi przez technologie wspomagające.</li><li>Jeśli system prosi o ograniczenie ruchu, animacje są wyłączone i od razu widać statyczny stan końcowy.</li><li>Lekkie strony bez narzędzi śledzących, które szybko ładują się nawet przy słabym połączeniu.</li></ul>` },
  { h: 'Znane ograniczenia', body: ps('Opinie w Google zostały opublikowane po angielsku. Na stronie pokazuję oznaczone tłumaczenie, a pod nim oryginał. Oba teksty mają właściwy kod języka, więc czytniki ekranu używają poprawnej wymowy.') },
  { h: 'Znalazłeś problem?', body: ps(`Jeżeli coś nie działa prawidłowo, napisz do mnie na ${E} lub zadzwoń pod ${P}. Odpowiem możliwie szybko i w razie potrzeby pomogę znaleźć inny sposób dostępu do potrzebnych informacji.`) }
]}
}
};
